// Generated by scripts/bake-era-palettes.mjs - do not edit by hand.
//
// Visualizer colours for the era images under the API site's /assets/, which
// are served without CORS and so can't be sampled in the browser. An image
// missing from here falls back to the accent colour; rerun the script to add it.

import type { RGB } from './viz/types'

export const ERA_PALETTES: Readonly<Record<string, RGB[]>> = {
  '/assets/999.jpg': [{ r: 218, g: 83, b: 72 }, { r: 218, g: 166, b: 72 }, { r: 188, g: 218, b: 72 }, { r: 105, g: 218, b: 72 }],
  '/assets/aff.jpg': [{ r: 219, g: 219, b: 219 }, { r: 102, g: 102, b: 102 }, { r: 168, g: 168, b: 168 }, { r: 242, g: 242, b: 242 }],
  '/assets/agats2_av.webp': [{ r: 15, g: 157, b: 240 }, { r: 210, g: 140, b: 137 }, { r: 144, g: 137, b: 210 }, { r: 200, g: 191, b: 65 }],
  '/assets/bdm.webp': [{ r: 219, g: 219, b: 219 }, { r: 102, g: 102, b: 102 }, { r: 168, g: 168, b: 168 }, { r: 242, g: 242, b: 242 }],
  '/assets/drfl.png': [{ r: 191, g: 89, b: 64 }, { r: 185, g: 70, b: 129 }, { r: 163, g: 70, b: 185 }, { r: 207, g: 172, b: 98 }],
  '/assets/drfl_tv.webp': [{ r: 185, g: 88, b: 70 }, { r: 185, g: 70, b: 129 }, { r: 169, g: 70, b: 185 }, { r: 194, g: 161, b: 94 }],
  '/assets/fd.webp': [{ r: 185, g: 70, b: 86 }, { r: 185, g: 70, b: 165 }, { r: 185, g: 114, b: 70 }, { r: 135, g: 70, b: 185 }],
  '/assets/gbgr.jpg': [{ r: 241, g: 218, b: 106 }, { r: 64, g: 152, b: 191 }, { r: 210, g: 137, b: 147 }, { r: 84, g: 70, b: 185 }],
  '/assets/gbgr_5yae.jpg': [{ r: 185, g: 137, b: 70 }, { r: 103, g: 133, b: 197 }, { r: 210, g: 139, b: 137 }, { r: 123, g: 70, b: 185 }],
  '/assets/gbgr_ae.jpg': [{ r: 235, g: 217, b: 112 }, { r: 71, g: 139, b: 185 }, { r: 210, g: 137, b: 140 }, { r: 110, g: 91, b: 193 }],
  '/assets/hih_999.webp': [{ r: 190, g: 65, b: 78 }, { r: 185, g: 70, b: 185 }, { r: 186, g: 190, b: 65 }, { r: 115, g: 190, b: 65 }],
  '/assets/jute.png': [{ r: 215, g: 174, b: 83 }, { r: 187, g: 137, b: 210 }, { r: 137, g: 169, b: 210 }, { r: 145, g: 137, b: 210 }],
  '/assets/kills.webp': [{ r: 246, g: 9, b: 23 }, { r: 185, g: 133, b: 70 }, { r: 229, g: 246, b: 9 }, { r: 94, g: 246, b: 9 }],
  '/assets/live.webp': [{ r: 70, g: 170, b: 185 }, { r: 70, g: 107, b: 185 }, { r: 137, g: 210, b: 183 }, { r: 165, g: 70, b: 185 }],
  '/assets/lnd.jpg': [{ r: 216, g: 96, b: 118 }, { r: 185, g: 70, b: 159 }, { r: 201, g: 149, b: 104 }, { r: 127, g: 70, b: 185 }],
  '/assets/lnd_5yae.webp': [{ r: 189, g: 131, b: 66 }, { r: 196, g: 206, b: 127 }, { r: 70, g: 129, b: 185 }, { r: 185, g: 70, b: 79 }],
  '/assets/lnd_eov.webp': [{ r: 216, g: 96, b: 118 }, { r: 185, g: 70, b: 159 }, { r: 200, g: 147, b: 103 }, { r: 127, g: 70, b: 185 }],
  '/assets/mainstream.jpg': [{ r: 227, g: 51, b: 28 }, { r: 95, g: 203, b: 215 }, { r: 186, g: 159, b: 73 }, { r: 112, g: 201, b: 159 }],
  '/assets/nd.webp': [{ r: 185, g: 86, b: 70 }, { r: 185, g: 70, b: 118 }, { r: 84, g: 70, b: 185 }, { r: 164, g: 70, b: 185 }],
  '/assets/outsiderz.png': [{ r: 219, g: 219, b: 219 }, { r: 104, g: 104, b: 104 }, { r: 168, g: 168, b: 168 }, { r: 242, g: 242, b: 242 }],
  '/assets/posthumous.png': [{ r: 70, g: 127, b: 185 }, { r: 188, g: 80, b: 80 }, { r: 143, g: 70, b: 185 }, { r: 185, g: 70, b: 162 }],
  '/assets/smule.png': [{ r: 107, g: 196, b: 59 }, { r: 206, g: 126, b: 126 }, { r: 59, g: 196, b: 166 }, { r: 59, g: 148, b: 196 }],
  '/assets/soundcloud.jpg': [{ r: 248, g: 157, b: 75 }, { r: 240, g: 248, b: 75 }, { r: 142, g: 248, b: 75 }, { r: 75, g: 248, b: 106 }],
  '/assets/tpne.webp': [{ r: 185, g: 121, b: 70 }, { r: 164, g: 70, b: 185 }, { r: 103, g: 147, b: 197 }, { r: 185, g: 70, b: 80 }],
  '/assets/tpp.webp': [{ r: 8, g: 183, b: 247 }, { r: 227, g: 28, b: 145 }, { r: 248, g: 231, b: 99 }, { r: 20, g: 235, b: 124 }],
  '/assets/tpp_ee.webp': [{ r: 8, g: 183, b: 247 }, { r: 227, g: 28, b: 145 }, { r: 248, g: 231, b: 99 }, { r: 20, g: 235, b: 124 }],
  '/assets/ttz.webp': [{ r: 70, g: 127, b: 185 }, { r: 70, g: 185, b: 122 }, { r: 180, g: 188, b: 80 }, { r: 96, g: 185, b: 70 }],
  '/assets/wod.jpg': [{ r: 213, g: 189, b: 116 }, { r: 211, g: 136, b: 146 }, { r: 93, g: 181, b: 193 }, { r: 156, g: 200, b: 110 }],
  '/assets/wtla.webp': [{ r: 210, g: 210, b: 137 }, { r: 70, g: 171, b: 185 }, { r: 196, g: 151, b: 100 }, { r: 130, g: 208, b: 167 }],
  '/assets/youtube.webp': [{ r: 249, g: 8, b: 8 }, { r: 249, g: 144, b: 8 }, { r: 217, g: 249, b: 8 }, { r: 80, g: 249, b: 8 }],
}
