// Reactions travel as shortcode names ("fire"), so every client renders the
// same glyph for them. Anything not in this table is shown as sent.
export const EMOJI: Record<string, string> = {
  fire: '🔥', heart: '❤️', purple_heart: '💜', broken_heart: '💔', joy: '😂', rofl: '🤣', skull: '💀',
  sob: '😭', eyes: '👀', thumbsup: '👍', thumbsdown: '👎', pray: '🙏', clap: '👏', raised_hands: '🙌',
  muscle: '💪', ok_hand: '👌', wave: '👋', '100': '💯', tada: '🎉', sparkles: '✨', star: '⭐',
  rocket: '🚀', goat: '🐐', crown: '👑', gem: '💎', zap: '⚡', headphones: '🎧', musical_note: '🎵',
  microphone: '🎤', cd: '💿', thinking: '🤔', smile: '😄', grin: '😁', wink: '😉', heart_eyes: '😍',
  sunglasses: '😎', flushed: '😳', cry: '😢', rage: '😡', sweat_smile: '😅', shushing: '🤫', salute: '🫡',
  white_check_mark: '✅', x: '❌', warning: '⚠️', bangbang: '‼️', question: '❓', pushpin: '📌', lock: '🔒',

  // Expanded set (faces, gestures, hearts, animals, food, activities, travel, objects, symbols)
  relaxed: '☺️', blush: '😊', innocent: '😇', star_struck: '🤩', kissing_heart: '😘', yum: '😋',
  stuck_out_tongue: '😛', stuck_out_tongue_winking_eye: '😜', zany_face: '🤪', partying_face: '🥳',
  upside_down_face: '🙃', money_mouth_face: '🤑', nerd_face: '🤓', face_with_monocle: '🧐',
  smirk: '😏', unamused: '😒', roll_eyes: '🙄', grimacing: '😬', relieved: '😌', pensive: '😔',
  sleepy: '😪', drooling_face: '🤤', sleeping: '😴', mask: '😷', face_with_thermometer: '🤒',
  face_with_head_bandage: '🤕', nauseated_face: '🤢', vomiting_face: '🤮', sneezing_face: '🤧',
  hot_face: '🥵', cold_face: '🥶', woozy_face: '🥴', dizzy_face: '😵', exploding_head: '🤯',
  cowboy_hat_face: '🤠', clown_face: '🤡', smiling_imp: '😈', imp: '👿', japanese_ogre: '👹',
  japanese_goblin: '👺', ghost: '👻', alien: '👽', robot: '🤖', hushed: '😯', frowning: '😦',
  anguished: '😧', fearful: '😨', cold_sweat: '😰', scream: '😱', astonished: '😲', confused: '😕',
  worried: '😟', slightly_frowning_face: '🙁', persevere: '😣', confounded: '😖', tired_face: '😫',
  weary: '😩', triumph: '😤', angry: '😠', pouting_face: '😡', no_mouth: '😶', neutral_face: '😐',
  expressionless: '😑', zipper_mouth_face: '🤐', pleading_face: '🥺', hugging_face: '🤗',
  face_with_hand_over_mouth: '🤭', shushing_face: '🤫', face_with_raised_eyebrow: '🤨',
  yawning_face: '🥱', poop: '💩',

  victory_hand: '✌️', crossed_fingers: '🤞', love_you_gesture: '🤟', metal: '🤘', call_me_hand: '🤙',
  point_left: '👈', point_right: '👉', point_up_2: '👆', point_down: '👇', point_up: '☝️',
  middle_finger: '🖕', raised_hand: '✋', vulcan_salute: '🖖', writing_hand: '✍️', nail_care: '💅',
  selfie: '🤳', leg: '🦵', foot: '🦶', ear: '👂', nose: '👃', brain: '🧠', eye: '👁️', tongue: '👅',
  lips: '👄', tooth: '🦷', baby: '👶', boy: '👦', girl: '👧', man: '👨', woman: '👩',
  older_man: '👴', older_woman: '👵', detective: '🕵️',

  blue_heart: '💙', green_heart: '💚', yellow_heart: '💛', orange_heart: '🧡', black_heart: '🖤',
  white_heart: '🤍', brown_heart: '🤎', two_hearts: '💕', heartpulse: '💗', heartbeat: '💓',
  sparkling_heart: '💖', cupid: '💘', gift_heart: '💝', revolving_hearts: '💞',
  heart_decoration: '💟', kiss: '💋',

  dog: '🐶', cat: '🐱', mouse: '🐭', hamster: '🐹', rabbit: '🐰', fox_face: '🦊', bear: '🐻',
  panda_face: '🐼', koala: '🐨', tiger: '🐯', lion: '🦁', cow: '🐮', pig: '🐷', frog: '🐸',
  monkey_face: '🐵', chicken: '🐔', penguin: '🐧', bird: '🐦', baby_chick: '🐤', eagle: '🦅',
  duck: '🦆', owl: '🦉', bat: '🦇', wolf: '🐺', horse: '🐴', unicorn: '🦄', bee: '🐝', bug: '🐛',
  butterfly: '🦋', snail: '🐌', snake: '🐍', turtle: '🐢', octopus: '🐙', fish: '🐟',
  dolphin: '🐬', whale: '🐳', shark: '🦈', elephant: '🐘', giraffe_face: '🦒', zebra_face: '🦓',
  dragon_face: '🐲', paw_prints: '🐾',

  apple: '🍎', pizza: '🍕', hamburger: '🍔', fries: '🍟', hotdog: '🌭', taco: '🌮', burrito: '🌯',
  popcorn: '🍿', doughnut: '🍩', cookie: '🍪', birthday: '🎂', cake: '🍰', icecream: '🍦',
  candy: '🍬', lollipop: '🍭', chocolate_bar: '🍫', grapes: '🍇', watermelon: '🍉',
  strawberry: '🍓', banana: '🍌', peach: '🍑', cherries: '🍒', lemon: '🍋', avocado: '🥑',
  carrot: '🥕', corn: '🌽', bread: '🍞', cheese: '🧀', egg: '🥚', bacon: '🥓', sushi: '🍣',
  ramen: '🍜', coffee: '☕', tea: '🍵', beer: '🍺', beers: '🍻', wine_glass: '🍷', cocktail: '🍸',
  tropical_drink: '🍹', champagne: '🍾', baby_bottle: '🍼', eggplant: '🍆',

  soccer: '⚽', basketball: '🏀', football: '🏈', baseball: '⚾', tennis: '🎾', volleyball: '🏐',
  '8ball': '🎱', bowling: '🎳', golf: '⛳', boxing_glove: '🥊', trophy: '🏆', medal_sports: '🏅',
  first_place: '🥇', dart: '🎯', video_game: '🎮', game_die: '🎲', chess_pawn: '♟️',
  jigsaw: '🧩', guitar: '🎸', violin: '🎻', trumpet: '🎺', saxophone: '🎷', drum: '🥁',
  dancer: '💃', dancers: '👯',

  car: '🚗', taxi: '🚕', bus: '🚌', airplane: '✈️', helicopter: '🚁', train: '🚆', ship: '🚢',
  anchor: '⚓', bike: '🚲', motorcycle: '🏍️', world_map: '🗺️', mountain: '⛰️', camping: '🏕️',
  beach_umbrella: '🏖️', desert_island: '🏝️', stadium: '🏟️', moon: '🌙', sun_with_face: '🌞',
  full_moon: '🌕', earth_americas: '🌎', cloud: '☁️', sun_behind_cloud: '⛅',
  cloud_with_rain: '🌧️', snowflake: '❄️', snowman: '⛄', rainbow: '🌈', droplet: '💧',
  ocean_wave: '🌊', tornado: '🌪️', four_leaf_clover: '🍀', maple_leaf: '🍁', cactus: '🌵',
  palm_tree: '🌴', evergreen_tree: '🌲', rose: '🌹', tulip: '🌷', sunflower: '🌻',
  cherry_blossom: '🌸',

  tv: '📺', camera: '📷', iphone: '📱', computer: '💻', keyboard: '⌨️', battery: '🔋',
  electric_plug: '🔌', bulb: '💡', flashlight: '🔦', candle: '🕯️', money_with_wings: '💸',
  dollar: '💵', moneybag: '💰', credit_card: '💳', gift: '🎁', balloon: '🎈',
  confetti_ball: '🎊', ribbon: '🎀', bell: '🔔', mega: '📣', loudspeaker: '📢', bookmark: '🔖',
  book: '📖', newspaper: '📰', pencil2: '✏️', paperclip: '📎', scissors: '✂️', hammer: '🔨',
  wrench: '🔧', gear: '⚙️', link: '🔗', key: '🔑', hourglass: '⌛', alarm_clock: '⏰',
  calendar: '📅', umbrella: '☂️', sunglasses_obj: '🕶️', shirt: '👕', jeans: '👖', shoe: '👞',

  heavy_check_mark: '✔️', heavy_multiplication_x: '✖️', no_entry: '⛔', no_entry_sign: '🚫',
  exclamation: '❗', grey_exclamation: '❕', grey_question: '❔', heavy_plus_sign: '➕',
  heavy_minus_sign: '➖', infinity: '♾️', recycle: '♻️', radioactive: '☢️', peace: '☮️',
  yin_yang: '☯️', om: '🕉️', wheelchair: '♿', id: '🆔', new: '🆕', ok: '🆗', sos: '🆘', up: '🆙',
  cool: '🆒', free: '🆓', abc: '🔤', arrow_right: '➡️', arrow_left: '⬅️', arrow_up: '⬆️',
  arrow_down: '⬇️', arrows_counterclockwise: '🔄', repeat: '🔁', shuffle: '🔀',
  fast_forward: '⏩', rewind: '⏪', play_pause: '⏯️', musical_notes: '🎶',
  speaker_high_volume: '🔊', mute: '🔇', vibration_mode: '📳', clock: '🕐', rainbow_flag: '🏳️‍🌈',

  // Full Apple emoji set (auto-generated, minus flags/people already covered above)
  hash: '#️⃣', keycap_star: '*️⃣', zero: '0️⃣', one: '1️⃣', two: '2️⃣',
  three: '3️⃣', four: '4️⃣', five: '5️⃣', six: '6️⃣', seven: '7️⃣',
  eight: '8️⃣', nine: '9️⃣', copyright: '©️', registered: '®️', mahjong: '🀄',
  black_joker: '🃏', a: '🅰️', b: '🅱️', o2: '🅾️', parking: '🅿️',
  ab: '🆎', cl: '🆑', ng: '🆖', vs: '🆚', flag_ac: '🇦🇨',
  flag_ad: '🇦🇩', flag_ae: '🇦🇪', flag_af: '🇦🇫', flag_ag: '🇦🇬', flag_ai: '🇦🇮',
  flag_al: '🇦🇱', flag_am: '🇦🇲', flag_ao: '🇦🇴', flag_aq: '🇦🇶', flag_ar: '🇦🇷',
  flag_as: '🇦🇸', flag_at: '🇦🇹', flag_au: '🇦🇺', flag_aw: '🇦🇼', flag_ax: '🇦🇽',
  flag_az: '🇦🇿', flag_ba: '🇧🇦', flag_bb: '🇧🇧', flag_bd: '🇧🇩', flag_be: '🇧🇪',
  flag_bf: '🇧🇫', flag_bg: '🇧🇬', flag_bh: '🇧🇭', flag_bi: '🇧🇮', flag_bj: '🇧🇯',
  flag_bl: '🇧🇱', flag_bm: '🇧🇲', flag_bn: '🇧🇳', flag_bo: '🇧🇴', flag_bq: '🇧🇶',
  flag_br: '🇧🇷', flag_bs: '🇧🇸', flag_bt: '🇧🇹', flag_bv: '🇧🇻', flag_bw: '🇧🇼',
  flag_by: '🇧🇾', flag_bz: '🇧🇿', flag_ca: '🇨🇦', flag_cc: '🇨🇨', flag_cd: '🇨🇩',
  flag_cf: '🇨🇫', flag_cg: '🇨🇬', flag_ch: '🇨🇭', flag_ci: '🇨🇮', flag_ck: '🇨🇰',
  flag_cl: '🇨🇱', flag_cm: '🇨🇲', cn: '🇨🇳', flag_co: '🇨🇴', flag_cp: '🇨🇵',
  flag_sark: '🇨🇶', flag_cr: '🇨🇷', flag_cu: '🇨🇺', flag_cv: '🇨🇻', flag_cw: '🇨🇼',
  flag_cx: '🇨🇽', flag_cy: '🇨🇾', flag_cz: '🇨🇿', de: '🇩🇪', flag_dg: '🇩🇬',
  flag_dj: '🇩🇯', flag_dk: '🇩🇰', flag_dm: '🇩🇲', flag_do: '🇩🇴', flag_dz: '🇩🇿',
  flag_ea: '🇪🇦', flag_ec: '🇪🇨', flag_ee: '🇪🇪', flag_eg: '🇪🇬', flag_eh: '🇪🇭',
  flag_er: '🇪🇷', es: '🇪🇸', flag_et: '🇪🇹', flag_eu: '🇪🇺', flag_fi: '🇫🇮',
  flag_fj: '🇫🇯', flag_fk: '🇫🇰', flag_fm: '🇫🇲', flag_fo: '🇫🇴', fr: '🇫🇷',
  flag_ga: '🇬🇦', gb: '🇬🇧', flag_gd: '🇬🇩', flag_ge: '🇬🇪', flag_gf: '🇬🇫',
  flag_gg: '🇬🇬', flag_gh: '🇬🇭', flag_gi: '🇬🇮', flag_gl: '🇬🇱', flag_gm: '🇬🇲',
  flag_gn: '🇬🇳', flag_gp: '🇬🇵', flag_gq: '🇬🇶', flag_gr: '🇬🇷', flag_gs: '🇬🇸',
  flag_gt: '🇬🇹', flag_gu: '🇬🇺', flag_gw: '🇬🇼', flag_gy: '🇬🇾', flag_hk: '🇭🇰',
  flag_hm: '🇭🇲', flag_hn: '🇭🇳', flag_hr: '🇭🇷', flag_ht: '🇭🇹', flag_hu: '🇭🇺',
  flag_ic: '🇮🇨', flag_id: '🇮🇩', flag_ie: '🇮🇪', flag_il: '🇮🇱', flag_im: '🇮🇲',
  flag_in: '🇮🇳', flag_io: '🇮🇴', flag_iq: '🇮🇶', flag_ir: '🇮🇷', flag_is: '🇮🇸',
  it: '🇮🇹', flag_je: '🇯🇪', flag_jm: '🇯🇲', flag_jo: '🇯🇴', jp: '🇯🇵',
  flag_ke: '🇰🇪', flag_kg: '🇰🇬', flag_kh: '🇰🇭', flag_ki: '🇰🇮', flag_km: '🇰🇲',
  flag_kn: '🇰🇳', flag_kp: '🇰🇵', kr: '🇰🇷', flag_kw: '🇰🇼', flag_ky: '🇰🇾',
  flag_kz: '🇰🇿', flag_la: '🇱🇦', flag_lb: '🇱🇧', flag_lc: '🇱🇨', flag_li: '🇱🇮',
  flag_lk: '🇱🇰', flag_lr: '🇱🇷', flag_ls: '🇱🇸', flag_lt: '🇱🇹', flag_lu: '🇱🇺',
  flag_lv: '🇱🇻', flag_ly: '🇱🇾', flag_ma: '🇲🇦', flag_mc: '🇲🇨', flag_md: '🇲🇩',
  flag_me: '🇲🇪', flag_mf: '🇲🇫', flag_mg: '🇲🇬', flag_mh: '🇲🇭', flag_mk: '🇲🇰',
  flag_ml: '🇲🇱', flag_mm: '🇲🇲', flag_mn: '🇲🇳', flag_mo: '🇲🇴', flag_mp: '🇲🇵',
  flag_mq: '🇲🇶', flag_mr: '🇲🇷', flag_ms: '🇲🇸', flag_mt: '🇲🇹', flag_mu: '🇲🇺',
  flag_mv: '🇲🇻', flag_mw: '🇲🇼', flag_mx: '🇲🇽', flag_my: '🇲🇾', flag_mz: '🇲🇿',
  flag_na: '🇳🇦', flag_nc: '🇳🇨', flag_ne: '🇳🇪', flag_nf: '🇳🇫', flag_ng: '🇳🇬',
  flag_ni: '🇳🇮', flag_nl: '🇳🇱', flag_no: '🇳🇴', flag_np: '🇳🇵', flag_nr: '🇳🇷',
  flag_nu: '🇳🇺', flag_nz: '🇳🇿', flag_om: '🇴🇲', flag_pa: '🇵🇦', flag_pe: '🇵🇪',
  flag_pf: '🇵🇫', flag_pg: '🇵🇬', flag_ph: '🇵🇭', flag_pk: '🇵🇰', flag_pl: '🇵🇱',
  flag_pm: '🇵🇲', flag_pn: '🇵🇳', flag_pr: '🇵🇷', flag_ps: '🇵🇸', flag_pt: '🇵🇹',
  flag_pw: '🇵🇼', flag_py: '🇵🇾', flag_qa: '🇶🇦', flag_re: '🇷🇪', flag_ro: '🇷🇴',
  flag_rs: '🇷🇸', ru: '🇷🇺', flag_rw: '🇷🇼', flag_sa: '🇸🇦', flag_sb: '🇸🇧',
  flag_sc: '🇸🇨', flag_sd: '🇸🇩', flag_se: '🇸🇪', flag_sg: '🇸🇬', flag_sh: '🇸🇭',
  flag_si: '🇸🇮', flag_sj: '🇸🇯', flag_sk: '🇸🇰', flag_sl: '🇸🇱', flag_sm: '🇸🇲',
  flag_sn: '🇸🇳', flag_so: '🇸🇴', flag_sr: '🇸🇷', flag_ss: '🇸🇸', flag_st: '🇸🇹',
  flag_sv: '🇸🇻', flag_sx: '🇸🇽', flag_sy: '🇸🇾', flag_sz: '🇸🇿', flag_ta: '🇹🇦',
  flag_tc: '🇹🇨', flag_td: '🇹🇩', flag_tf: '🇹🇫', flag_tg: '🇹🇬', flag_th: '🇹🇭',
  flag_tj: '🇹🇯', flag_tk: '🇹🇰', flag_tl: '🇹🇱', flag_tm: '🇹🇲', flag_tn: '🇹🇳',
  flag_to: '🇹🇴', flag_tr: '🇹🇷', flag_tt: '🇹🇹', flag_tv: '🇹🇻', flag_tw: '🇹🇼',
  flag_tz: '🇹🇿', flag_ua: '🇺🇦', flag_ug: '🇺🇬', flag_um: '🇺🇲', flag_un: '🇺🇳',
  us: '🇺🇸', flag_uy: '🇺🇾', flag_uz: '🇺🇿', flag_va: '🇻🇦', flag_vc: '🇻🇨',
  flag_ve: '🇻🇪', flag_vg: '🇻🇬', flag_vi: '🇻🇮', flag_vn: '🇻🇳', flag_vu: '🇻🇺',
  flag_wf: '🇼🇫', flag_ws: '🇼🇸', flag_xk: '🇽🇰', flag_ye: '🇾🇪', flag_yt: '🇾🇹',
  flag_za: '🇿🇦', flag_zm: '🇿🇲', flag_zw: '🇿🇼', koko: '🈁', sa: '🈂️',
  u7121: '🈚', u6307: '🈯', u7981: '🈲', u7a7a: '🈳', u5408: '🈴',
  u6e80: '🈵', u6709: '🈶', u6708: '🈷️', u7533: '🈸', u5272: '🈹',
  u55b6: '🈺', ideograph_advantage: '🉐', accept: '🉑', cyclone: '🌀', foggy: '🌁',
  closed_umbrella: '🌂', night_with_stars: '🌃', sunrise_over_mountains: '🌄', sunrise: '🌅', city_sunset: '🌆',
  city_sunrise: '🌇', bridge_at_night: '🌉', volcano: '🌋', milky_way: '🌌', earth_africa: '🌍',
  earth_asia: '🌏', globe_with_meridians: '🌐', new_moon: '🌑', waxing_crescent_moon: '🌒', first_quarter_moon: '🌓',
  moon_2: '🌔', waning_gibbous_moon: '🌖', last_quarter_moon: '🌗', waning_crescent_moon: '🌘', new_moon_with_face: '🌚',
  first_quarter_moon_with_face: '🌛', last_quarter_moon_with_face: '🌜', full_moon_with_face: '🌝', star2: '🌟', stars: '🌠',
  thermometer: '🌡️', mostly_sunny: '🌤️', barely_sunny: '🌥️', partly_sunny_rain: '🌦️', snow_cloud: '🌨️',
  lightning: '🌩️', fog: '🌫️', wind_blowing_face: '🌬️', chestnut: '🌰', seedling: '🌱',
  deciduous_tree: '🌳', hot_pepper: '🌶️', hibiscus: '🌺', blossom: '🌼', ear_of_rice: '🌾',
  herb: '🌿', fallen_leaf: '🍂', leaves: '🍃', brown_mushroom: '🍄‍🟫', mushroom: '🍄',
  tomato: '🍅', melon: '🍈', tangerine: '🍊', lime: '🍋‍🟩', pineapple: '🍍',
  green_apple: '🍏', pear: '🍐', meat_on_bone: '🍖', poultry_leg: '🍗', rice_cracker: '🍘',
  rice_ball: '🍙', rice: '🍚', curry: '🍛', spaghetti: '🍝', sweet_potato: '🍠',
  dango: '🍡', oden: '🍢', fried_shrimp: '🍤', fish_cake: '🍥', shaved_ice: '🍧',
  ice_cream: '🍨', custard: '🍮', honey_pot: '🍯', bento: '🍱', stew: '🍲',
  fried_egg: '🍳', fork_and_knife: '🍴', sake: '🍶', knife_fork_plate: '🍽️', jack_o_lantern: '🎃',
  christmas_tree: '🎄', santa: '🎅', fireworks: '🎆', sparkler: '🎇', tanabata_tree: '🎋',
  crossed_flags: '🎌', bamboo: '🎍', dolls: '🎎', flags: '🎏', wind_chime: '🎐',
  rice_scene: '🎑', school_satchel: '🎒', mortar_board: '🎓', medal: '🎖️', reminder_ribbon: '🎗️',
  studio_microphone: '🎙️', level_slider: '🎚️', control_knobs: '🎛️', film_frames: '🎞️', admission_tickets: '🎟️',
  carousel_horse: '🎠', ferris_wheel: '🎡', roller_coaster: '🎢', fishing_pole_and_fish: '🎣', movie_camera: '🎥',
  cinema: '🎦', art: '🎨', tophat: '🎩', circus_tent: '🎪', ticket: '🎫',
  clapper: '🎬', performing_arts: '🎭', slot_machine: '🎰', flower_playing_cards: '🎴', musical_keyboard: '🎹',
  musical_score: '🎼', running_shirt_with_sash: '🎽', ski: '🎿', checkered_flag: '🏁', snowboarder: '🏂',
  woman_running: '🏃‍♀️', woman_running_facing_right: '🏃‍♀️‍➡️', man_running: '🏃‍♂️', man_running_facing_right: '🏃‍♂️‍➡️', person_running_facing_right: '🏃‍➡️',
  runner: '🏃', woman_surfing: '🏄‍♀️', man_surfing: '🏄‍♂️', surfer: '🏄', horse_racing: '🏇',
  rugby_football: '🏉', woman_swimming: '🏊‍♀️', man_swimming: '🏊‍♂️', swimmer: '🏊', woman_lifting_weights: '🏋️‍♀️',
  man_lifting_weights: '🏋️‍♂️', weight_lifter: '🏋️', woman_golfing: '🏌️‍♀️', man_golfing: '🏌️‍♂️', golfer: '🏌️',
  racing_car: '🏎️', cricket_bat_and_ball: '🏏', field_hockey_stick_and_ball: '🏑', ice_hockey_stick_and_puck: '🏒', table_tennis_paddle_and_ball: '🏓',
  snow_capped_mountain: '🏔️', building_construction: '🏗️', house_buildings: '🏘️', cityscape: '🏙️', derelict_house_building: '🏚️',
  classical_building: '🏛️', desert: '🏜️', national_park: '🏞️', house: '🏠', house_with_garden: '🏡',
  office: '🏢', post_office: '🏣', european_post_office: '🏤', hospital: '🏥', bank: '🏦',
  atm: '🏧', hotel: '🏨', love_hotel: '🏩', convenience_store: '🏪', school: '🏫',
  department_store: '🏬', factory: '🏭', izakaya_lantern: '🏮', japanese_castle: '🏯', european_castle: '🏰',
  transgender_flag: '🏳️‍⚧️', waving_white_flag: '🏳️', pirate_flag: '🏴‍☠️', flag_england: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', flag_scotland: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  flag_wales: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', waving_black_flag: '🏴', rosette: '🏵️', label: '🏷️', badminton_racquet_and_shuttlecock: '🏸',
  bow_and_arrow: '🏹', amphora: '🏺', rat: '🐀', mouse2: '🐁', ox: '🐂',
  water_buffalo: '🐃', cow2: '🐄', tiger2: '🐅', leopard: '🐆', rabbit2: '🐇',
  black_cat: '🐈‍⬛', cat2: '🐈', dragon: '🐉', crocodile: '🐊', whale2: '🐋',
  racehorse: '🐎', ram: '🐏', sheep: '🐑', monkey: '🐒', rooster: '🐓',
  service_dog: '🐕‍🦺', dog2: '🐕', pig2: '🐖', boar: '🐗', shell: '🐚',
  ant: '🐜', ladybug: '🐞', tropical_fish: '🐠', blowfish: '🐡', hatching_chick: '🐣',
  hatched_chick: '🐥', phoenix: '🐦‍🔥', black_bird: '🐦‍⬛', poodle: '🐩', dromedary_camel: '🐪',
  camel: '🐫', polar_bear: '🐻‍❄️', pig_nose: '🐽', chipmunk: '🐿️', eye_in_speech_bubble: '👁️‍🗨️',
  facepunch: '👊', open_hands: '👐', womans_hat: '👒', eyeglasses: '👓', necktie: '👔',
  dress: '👗', kimono: '👘', bikini: '👙', womans_clothes: '👚', purse: '👛',
  handbag: '👜', pouch: '👝', athletic_shoe: '👟', high_heel: '👠', sandal: '👡',
  boot: '👢', footprints: '👣', bust_in_silhouette: '👤', busts_in_silhouette: '👥', male_farmer: '👨‍🌾',
  male_cook: '👨‍🍳', man_feeding_baby: '👨‍🍼', male_student: '👨‍🎓', male_singer: '👨‍🎤', male_artist: '👨‍🎨',
  male_teacher: '👨‍🏫', male_factory_worker: '👨‍🏭', man_boy_boy: '👨‍👦‍👦', man_boy: '👨‍👦', man_girl_boy: '👨‍👧‍👦',
  man_girl_girl: '👨‍👧‍👧', man_girl: '👨‍👧', man_man_boy: '👨‍👨‍👦', man_man_boy_boy: '👨‍👨‍👦‍👦', man_man_girl: '👨‍👨‍👧',
  man_man_girl_boy: '👨‍👨‍👧‍👦', man_man_girl_girl: '👨‍👨‍👧‍👧', man_woman_boy: '👨‍👩‍👦', man_woman_boy_boy: '👨‍👩‍👦‍👦', man_woman_girl: '👨‍👩‍👧',
  man_woman_girl_boy: '👨‍👩‍👧‍👦', man_woman_girl_girl: '👨‍👩‍👧‍👧', male_technologist: '👨‍💻', male_office_worker: '👨‍💼', male_mechanic: '👨‍🔧',
  male_scientist: '👨‍🔬', male_astronaut: '👨‍🚀', male_firefighter: '👨‍🚒', man_with_white_cane_facing_right: '👨‍🦯‍➡️', man_with_probing_cane: '👨‍🦯',
  red_haired_man: '👨‍🦰', curly_haired_man: '👨‍🦱', bald_man: '👨‍🦲', white_haired_man: '👨‍🦳', man_in_motorized_wheelchair_facing_right: '👨‍🦼‍➡️',
  man_in_motorized_wheelchair: '👨‍🦼', man_in_manual_wheelchair_facing_right: '👨‍🦽‍➡️', man_in_manual_wheelchair: '👨‍🦽', male_doctor: '👨‍⚕️', male_judge: '👨‍⚖️',
  male_pilot: '👨‍✈️', man_heart_man: '👨‍❤️‍👨', man_kiss_man: '👨‍❤️‍💋‍👨', female_farmer: '👩‍🌾', female_cook: '👩‍🍳',
  woman_feeding_baby: '👩‍🍼', female_student: '👩‍🎓', female_singer: '👩‍🎤', female_artist: '👩‍🎨', female_teacher: '👩‍🏫',
  female_factory_worker: '👩‍🏭', woman_boy_boy: '👩‍👦‍👦', woman_boy: '👩‍👦', woman_girl_boy: '👩‍👧‍👦', woman_girl_girl: '👩‍👧‍👧',
  woman_girl: '👩‍👧', woman_woman_boy: '👩‍👩‍👦', woman_woman_boy_boy: '👩‍👩‍👦‍👦', woman_woman_girl: '👩‍👩‍👧', woman_woman_girl_boy: '👩‍👩‍👧‍👦',
  woman_woman_girl_girl: '👩‍👩‍👧‍👧', female_technologist: '👩‍💻', female_office_worker: '👩‍💼', female_mechanic: '👩‍🔧', female_scientist: '👩‍🔬',
  female_astronaut: '👩‍🚀', female_firefighter: '👩‍🚒', woman_with_white_cane_facing_right: '👩‍🦯‍➡️', woman_with_probing_cane: '👩‍🦯', red_haired_woman: '👩‍🦰',
  curly_haired_woman: '👩‍🦱', bald_woman: '👩‍🦲', white_haired_woman: '👩‍🦳', woman_in_motorized_wheelchair_facing_right: '👩‍🦼‍➡️', woman_in_motorized_wheelchair: '👩‍🦼',
  woman_in_manual_wheelchair_facing_right: '👩‍🦽‍➡️', woman_in_manual_wheelchair: '👩‍🦽', female_doctor: '👩‍⚕️', female_judge: '👩‍⚖️', female_pilot: '👩‍✈️',
  woman_heart_man: '👩‍❤️‍👨', woman_heart_woman: '👩‍❤️‍👩', woman_kiss_man: '👩‍❤️‍💋‍👨', woman_kiss_woman: '👩‍❤️‍💋‍👩', family: '👪',
  man_and_woman_holding_hands: '👫', two_men_holding_hands: '👬', two_women_holding_hands: '👭', female_police_officer: '👮‍♀️', male_police_officer: '👮‍♂️',
  cop: '👮', women_with_bunny_ears_partying: '👯‍♀️', men_with_bunny_ears_partying: '👯‍♂️', woman_with_veil: '👰‍♀️', man_with_veil: '👰‍♂️',
  bride_with_veil: '👰', blond_haired_woman: '👱‍♀️', blond_haired_man: '👱‍♂️', person_with_blond_hair: '👱', man_with_gua_pi_mao: '👲',
  woman_wearing_turban: '👳‍♀️', man_wearing_turban: '👳‍♂️', man_with_turban: '👳', female_construction_worker: '👷‍♀️', male_construction_worker: '👷‍♂️',
  construction_worker: '👷', princess: '👸', angel: '👼', space_invader: '👾', woman_tipping_hand: '💁‍♀️',
  man_tipping_hand: '💁‍♂️', information_desk_person: '💁', female_guard: '💂‍♀️', male_guard: '💂‍♂️', guardsman: '💂',
  lipstick: '💄', woman_getting_massage: '💆‍♀️', man_getting_massage: '💆‍♂️', massage: '💆', woman_getting_haircut: '💇‍♀️',
  man_getting_haircut: '💇‍♂️', haircut: '💇', barber: '💈', syringe: '💉', pill: '💊',
  love_letter: '💌', ring: '💍', couplekiss: '💏', bouquet: '💐', couple_with_heart: '💑',
  wedding: '💒', diamond_shape_with_a_dot_inside: '💠', anger: '💢', bomb: '💣', zzz: '💤',
  boom: '💥', sweat_drops: '💦', dash: '💨', dizzy: '💫', speech_balloon: '💬',
  thought_balloon: '💭', white_flower: '💮', currency_exchange: '💱', heavy_dollar_sign: '💲', yen: '💴',
  euro: '💶', pound: '💷', chart: '💹', seat: '💺', briefcase: '💼',
  minidisc: '💽', floppy_disk: '💾', dvd: '📀', file_folder: '📁', open_file_folder: '📂',
  page_with_curl: '📃', page_facing_up: '📄', calendar_2: '📆', card_index: '📇', chart_with_upwards_trend: '📈',
  chart_with_downwards_trend: '📉', bar_chart: '📊', clipboard: '📋', round_pushpin: '📍', straight_ruler: '📏',
  triangular_ruler: '📐', bookmark_tabs: '📑', ledger: '📒', notebook: '📓', notebook_with_decorative_cover: '📔',
  closed_book: '📕', green_book: '📗', blue_book: '📘', orange_book: '📙', books: '📚',
  name_badge: '📛', scroll: '📜', memo: '📝', telephone_receiver: '📞', pager: '📟',
  fax: '📠', satellite_antenna: '📡', outbox_tray: '📤', inbox_tray: '📥', package: '📦',
  e_mail: '📧', incoming_envelope: '📨', envelope_with_arrow: '📩', mailbox_closed: '📪', mailbox: '📫',
  mailbox_with_mail: '📬', mailbox_with_no_mail: '📭', postbox: '📮', postal_horn: '📯', calling: '📲',
  mobile_phone_off: '📴', no_mobile_phones: '📵', signal_strength: '📶', camera_with_flash: '📸', video_camera: '📹',
  radio: '📻', vhs: '📼', film_projector: '📽️', prayer_beads: '📿', repeat_one: '🔂',
  arrows_clockwise: '🔃', low_brightness: '🔅', high_brightness: '🔆', speaker: '🔈', sound: '🔉',
  mag: '🔍', mag_right: '🔎', lock_with_ink_pen: '🔏', closed_lock_with_key: '🔐', unlock: '🔓',
  no_bell: '🔕', radio_button: '🔘', back: '🔙', end: '🔚', on: '🔛',
  soon: '🔜', top: '🔝', underage: '🔞', keycap_ten: '🔟', capital_abcd: '🔠',
  abcd: '🔡', '1234': '🔢', symbols: '🔣', nut_and_bolt: '🔩', hocho: '🔪',
  gun: '🔫', microscope: '🔬', telescope: '🔭', crystal_ball: '🔮', six_pointed_star: '🔯',
  beginner: '🔰', trident: '🔱', black_square_button: '🔲', white_square_button: '🔳', red_circle: '🔴',
  large_blue_circle: '🔵', large_orange_diamond: '🔶', large_blue_diamond: '🔷', small_orange_diamond: '🔸', small_blue_diamond: '🔹',
  small_red_triangle: '🔺', small_red_triangle_down: '🔻', arrow_up_small: '🔼', arrow_down_small: '🔽', dove_of_peace: '🕊️',
  kaaba: '🕋', mosque: '🕌', synagogue: '🕍', menorah_with_nine_branches: '🕎', clock2: '🕑',
  clock3: '🕒', clock4: '🕓', clock5: '🕔', clock6: '🕕', clock7: '🕖',
  clock8: '🕗', clock9: '🕘', clock10: '🕙', clock11: '🕚', clock12: '🕛',
  clock130: '🕜', clock230: '🕝', clock330: '🕞', clock430: '🕟', clock530: '🕠',
  clock630: '🕡', clock730: '🕢', clock830: '🕣', clock930: '🕤', clock1030: '🕥',
  clock1130: '🕦', clock1230: '🕧', mantelpiece_clock: '🕰️', hole: '🕳️', man_in_business_suit_levitating: '🕴️',
  female_detective: '🕵️‍♀️', male_detective: '🕵️‍♂️', spider: '🕷️', spider_web: '🕸️', joystick: '🕹️',
  man_dancing: '🕺', linked_paperclips: '🖇️', lower_left_ballpoint_pen: '🖊️', lower_left_fountain_pen: '🖋️', lower_left_paintbrush: '🖌️',
  lower_left_crayon: '🖍️', raised_hand_with_fingers_splayed: '🖐️', desktop_computer: '🖥️', printer: '🖨️', three_button_mouse: '🖱️',
  trackball: '🖲️', frame_with_picture: '🖼️', card_index_dividers: '🗂️', card_file_box: '🗃️', file_cabinet: '🗄️',
  wastebasket: '🗑️', spiral_note_pad: '🗒️', spiral_calendar_pad: '🗓️', compression: '🗜️', old_key: '🗝️',
  rolled_up_newspaper: '🗞️', dagger_knife: '🗡️', speaking_head_in_silhouette: '🗣️', left_speech_bubble: '🗨️', right_anger_bubble: '🗯️',
  ballot_box_with_ballot: '🗳️', mount_fuji: '🗻', tokyo_tower: '🗼', statue_of_liberty: '🗽', japan: '🗾',
  moyai: '🗿', grinning: '😀', smiley: '😃', laughing: '😆', sweat: '😓',
  kissing: '😗', kissing_smiling_eyes: '😙', kissing_closed_eyes: '😚', stuck_out_tongue_closed_eyes: '😝', disappointed: '😞',
  disappointed_relieved: '😥', face_exhaling: '😮‍💨', open_mouth: '😮', face_with_spiral_eyes: '😵‍💫', face_in_clouds: '😶‍🌫️',
  smile_cat: '😸', joy_cat: '😹', smiley_cat: '😺', heart_eyes_cat: '😻', smirk_cat: '😼',
  kissing_cat: '😽', pouting_cat: '😾', crying_cat_face: '😿', scream_cat: '🙀', head_shaking_horizontally: '🙂‍↔️',
  head_shaking_vertically: '🙂‍↕️', slightly_smiling_face: '🙂', woman_gesturing_no: '🙅‍♀️', man_gesturing_no: '🙅‍♂️', no_good: '🙅',
  woman_gesturing_ok: '🙆‍♀️', man_gesturing_ok: '🙆‍♂️', ok_woman: '🙆', woman_bowing: '🙇‍♀️', man_bowing: '🙇‍♂️',
  bow: '🙇', see_no_evil: '🙈', hear_no_evil: '🙉', speak_no_evil: '🙊', woman_raising_hand: '🙋‍♀️',
  man_raising_hand: '🙋‍♂️', raising_hand: '🙋', woman_frowning: '🙍‍♀️', man_frowning: '🙍‍♂️', person_frowning: '🙍',
  woman_pouting: '🙎‍♀️', man_pouting: '🙎‍♂️', person_with_pouting_face: '🙎', steam_locomotive: '🚂', railway_car: '🚃',
  bullettrain_side: '🚄', bullettrain_front: '🚅', metro: '🚇', light_rail: '🚈', station: '🚉',
  tram: '🚊', train_2: '🚋', oncoming_bus: '🚍', trolleybus: '🚎', busstop: '🚏',
  minibus: '🚐', ambulance: '🚑', fire_engine: '🚒', police_car: '🚓', oncoming_police_car: '🚔',
  oncoming_taxi: '🚖', oncoming_automobile: '🚘', blue_car: '🚙', truck: '🚚', articulated_lorry: '🚛',
  tractor: '🚜', monorail: '🚝', mountain_railway: '🚞', suspension_railway: '🚟', mountain_cableway: '🚠',
  aerial_tramway: '🚡', woman_rowing_boat: '🚣‍♀️', man_rowing_boat: '🚣‍♂️', rowboat: '🚣', speedboat: '🚤',
  traffic_light: '🚥', vertical_traffic_light: '🚦', construction: '🚧', rotating_light: '🚨', triangular_flag_on_post: '🚩',
  door: '🚪', smoking: '🚬', no_smoking: '🚭', put_litter_in_its_place: '🚮', do_not_litter: '🚯',
  potable_water: '🚰', non_potable_water: '🚱', no_bicycles: '🚳', woman_biking: '🚴‍♀️', man_biking: '🚴‍♂️',
  bicyclist: '🚴', woman_mountain_biking: '🚵‍♀️', man_mountain_biking: '🚵‍♂️', mountain_bicyclist: '🚵', woman_walking: '🚶‍♀️',
  woman_walking_facing_right: '🚶‍♀️‍➡️', man_walking: '🚶‍♂️', man_walking_facing_right: '🚶‍♂️‍➡️', person_walking_facing_right: '🚶‍➡️', walking: '🚶',
  no_pedestrians: '🚷', children_crossing: '🚸', mens: '🚹', womens: '🚺', restroom: '🚻',
  baby_symbol: '🚼', toilet: '🚽', wc: '🚾', shower: '🚿', bath: '🛀',
  bathtub: '🛁', passport_control: '🛂', customs: '🛃', baggage_claim: '🛄', left_luggage: '🛅',
  couch_and_lamp: '🛋️', sleeping_accommodation: '🛌', shopping_bags: '🛍️', bellhop_bell: '🛎️', bed: '🛏️',
  place_of_worship: '🛐', octagonal_sign: '🛑', shopping_trolley: '🛒', hindu_temple: '🛕', hut: '🛖',
  elevator: '🛗', wireless: '🛜', playground_slide: '🛝', wheel: '🛞', ring_buoy: '🛟',
  hammer_and_wrench: '🛠️', shield: '🛡️', oil_drum: '🛢️', motorway: '🛣️', railway_track: '🛤️',
  motor_boat: '🛥️', small_airplane: '🛩️', airplane_departure: '🛫', airplane_arriving: '🛬', satellite: '🛰️',
  passenger_ship: '🛳️', scooter: '🛴', motor_scooter: '🛵', canoe: '🛶', sled: '🛷',
  flying_saucer: '🛸', skateboard: '🛹', auto_rickshaw: '🛺', pickup_truck: '🛻', roller_skate: '🛼',
  large_orange_circle: '🟠', large_yellow_circle: '🟡', large_green_circle: '🟢', large_purple_circle: '🟣', large_brown_circle: '🟤',
  large_red_square: '🟥', large_blue_square: '🟦', large_orange_square: '🟧', large_yellow_square: '🟨', large_green_square: '🟩',
  large_purple_square: '🟪', large_brown_square: '🟫', heavy_equals_sign: '🟰', pinched_fingers: '🤌', pinching_hand: '🤏',
  raised_back_of_hand: '🤚', left_facing_fist: '🤛', right_facing_fist: '🤜', handshake: '🤝', lying_face: '🤥',
  woman_facepalming: '🤦‍♀️', man_facepalming: '🤦‍♂️', face_palm: '🤦', face_with_symbols_on_mouth: '🤬', pregnant_woman: '🤰',
  breast_feeding: '🤱', palms_up_together: '🤲', prince: '🤴', woman_in_tuxedo: '🤵‍♀️', man_in_tuxedo: '🤵‍♂️',
  person_in_tuxedo: '🤵', mrs_claus: '🤶', woman_shrugging: '🤷‍♀️', man_shrugging: '🤷‍♂️', shrug: '🤷',
  woman_cartwheeling: '🤸‍♀️', man_cartwheeling: '🤸‍♂️', person_doing_cartwheel: '🤸', woman_juggling: '🤹‍♀️', man_juggling: '🤹‍♂️',
  juggling: '🤹', fencer: '🤺', woman_wrestling: '🤼‍♀️', man_wrestling: '🤼‍♂️', wrestlers: '🤼',
  woman_playing_water_polo: '🤽‍♀️', man_playing_water_polo: '🤽‍♂️', water_polo: '🤽', woman_playing_handball: '🤾‍♀️', man_playing_handball: '🤾‍♂️',
  handball: '🤾', diving_mask: '🤿', wilted_flower: '🥀', clinking_glasses: '🥂', tumbler_glass: '🥃',
  spoon: '🥄', goal_net: '🥅', second_place_medal: '🥈', third_place_medal: '🥉', martial_arts_uniform: '🥋',
  curling_stone: '🥌', lacrosse: '🥍', softball: '🥎', flying_disc: '🥏', croissant: '🥐',
  cucumber: '🥒', potato: '🥔', baguette_bread: '🥖', green_salad: '🥗', shallow_pan_of_food: '🥘',
  stuffed_flatbread: '🥙', glass_of_milk: '🥛', peanuts: '🥜', kiwifruit: '🥝', pancakes: '🥞',
  dumpling: '🥟', fortune_cookie: '🥠', takeout_box: '🥡', chopsticks: '🥢', bowl_with_spoon: '🥣',
  cup_with_straw: '🥤', coconut: '🥥', broccoli: '🥦', pie: '🥧', pretzel: '🥨',
  cut_of_meat: '🥩', sandwich: '🥪', canned_food: '🥫', leafy_green: '🥬', mango: '🥭',
  moon_cake: '🥮', bagel: '🥯', smiling_face_with_3_hearts: '🥰', smiling_face_with_tear: '🥲', ninja: '🥷',
  disguised_face: '🥸', face_holding_back_tears: '🥹', sari: '🥻', lab_coat: '🥼', goggles: '🥽',
  hiking_boot: '🥾', womans_flat_shoe: '🥿', crab: '🦀', scorpion: '🦂', turkey: '🦃',
  deer: '🦌', gorilla: '🦍', lizard: '🦎', rhinoceros: '🦏', shrimp: '🦐',
  squid: '🦑', hedgehog: '🦔', sauropod: '🦕', t_rex: '🦖', cricket: '🦗',
  kangaroo: '🦘', llama: '🦙', peacock: '🦚', hippopotamus: '🦛', parrot: '🦜',
  raccoon: '🦝', lobster: '🦞', mosquito: '🦟', microbe: '🦠', badger: '🦡',
  swan: '🦢', mammoth: '🦣', dodo: '🦤', sloth: '🦥', otter: '🦦',
  orangutan: '🦧', skunk: '🦨', flamingo: '🦩', oyster: '🦪', beaver: '🦫',
  bison: '🦬', seal: '🦭', guide_dog: '🦮', probing_cane: '🦯', bone: '🦴',
  female_superhero: '🦸‍♀️', male_superhero: '🦸‍♂️', superhero: '🦸', female_supervillain: '🦹‍♀️', male_supervillain: '🦹‍♂️',
  supervillain: '🦹', safety_vest: '🦺', ear_with_hearing_aid: '🦻', motorized_wheelchair: '🦼', manual_wheelchair: '🦽',
  mechanical_arm: '🦾', mechanical_leg: '🦿', cupcake: '🧁', salt: '🧂', beverage_box: '🧃',
  garlic: '🧄', onion: '🧅', falafel: '🧆', waffle: '🧇', butter: '🧈',
  mate_drink: '🧉', ice_cube: '🧊', bubble_tea: '🧋', troll: '🧌', woman_standing: '🧍‍♀️',
  man_standing: '🧍‍♂️', standing_person: '🧍', woman_kneeling: '🧎‍♀️', woman_kneeling_facing_right: '🧎‍♀️‍➡️', man_kneeling: '🧎‍♂️',
  man_kneeling_facing_right: '🧎‍♂️‍➡️', person_kneeling_facing_right: '🧎‍➡️', kneeling_person: '🧎', deaf_woman: '🧏‍♀️', deaf_man: '🧏‍♂️',
  deaf_person: '🧏', farmer: '🧑‍🌾', cook: '🧑‍🍳', person_feeding_baby: '🧑‍🍼', mx_claus: '🧑‍🎄',
  student: '🧑‍🎓', singer: '🧑‍🎤', artist: '🧑‍🎨', teacher: '🧑‍🏫', factory_worker: '🧑‍🏭',
  technologist: '🧑‍💻', office_worker: '🧑‍💼', mechanic: '🧑‍🔧', scientist: '🧑‍🔬', astronaut: '🧑‍🚀',
  firefighter: '🧑‍🚒', people_holding_hands: '🧑‍🤝‍🧑', person_with_white_cane_facing_right: '🧑‍🦯‍➡️', person_with_probing_cane: '🧑‍🦯', red_haired_person: '🧑‍🦰',
  curly_haired_person: '🧑‍🦱', bald_person: '🧑‍🦲', white_haired_person: '🧑‍🦳', person_in_motorized_wheelchair_facing_right: '🧑‍🦼‍➡️', person_in_motorized_wheelchair: '🧑‍🦼',
  person_in_manual_wheelchair_facing_right: '🧑‍🦽‍➡️', person_in_manual_wheelchair: '🧑‍🦽', family_adult_adult_child: '🧑‍🧑‍🧒', family_adult_adult_child_child: '🧑‍🧑‍🧒‍🧒', family_adult_child_child: '🧑‍🧒‍🧒',
  family_adult_child: '🧑‍🧒', health_worker: '🧑‍⚕️', judge: '🧑‍⚖️', pilot: '🧑‍✈️', adult: '🧑',
  child: '🧒', older_adult: '🧓', woman_with_beard: '🧔‍♀️', man_with_beard: '🧔‍♂️', bearded_person: '🧔',
  person_with_headscarf: '🧕', woman_in_steamy_room: '🧖‍♀️', man_in_steamy_room: '🧖‍♂️', person_in_steamy_room: '🧖', woman_climbing: '🧗‍♀️',
  man_climbing: '🧗‍♂️', person_climbing: '🧗', woman_in_lotus_position: '🧘‍♀️', man_in_lotus_position: '🧘‍♂️', person_in_lotus_position: '🧘',
  female_mage: '🧙‍♀️', male_mage: '🧙‍♂️', mage: '🧙', female_fairy: '🧚‍♀️', male_fairy: '🧚‍♂️',
  fairy: '🧚', female_vampire: '🧛‍♀️', male_vampire: '🧛‍♂️', vampire: '🧛', mermaid: '🧜‍♀️',
  merman: '🧜‍♂️', merperson: '🧜', female_elf: '🧝‍♀️', male_elf: '🧝‍♂️', elf: '🧝',
  female_genie: '🧞‍♀️', male_genie: '🧞‍♂️', genie: '🧞', female_zombie: '🧟‍♀️', male_zombie: '🧟‍♂️',
  zombie: '🧟', billed_cap: '🧢', scarf: '🧣', gloves: '🧤', coat: '🧥',
  socks: '🧦', red_envelope: '🧧', firecracker: '🧨', test_tube: '🧪', petri_dish: '🧫',
  dna: '🧬', compass: '🧭', abacus: '🧮', fire_extinguisher: '🧯', toolbox: '🧰',
  bricks: '🧱', magnet: '🧲', luggage: '🧳', lotion_bottle: '🧴', thread: '🧵',
  yarn: '🧶', safety_pin: '🧷', teddy_bear: '🧸', broom: '🧹', basket: '🧺',
  roll_of_paper: '🧻', soap: '🧼', sponge: '🧽', receipt: '🧾', nazar_amulet: '🧿',
  ballet_shoes: '🩰', one_piece_swimsuit: '🩱', briefs: '🩲', shorts: '🩳', thong_sandal: '🩴',
  light_blue_heart: '🩵', grey_heart: '🩶', pink_heart: '🩷', drop_of_blood: '🩸', adhesive_bandage: '🩹',
  stethoscope: '🩺', x_ray: '🩻', crutch: '🩼', yo_yo: '🪀', kite: '🪁',
  parachute: '🪂', boomerang: '🪃', magic_wand: '🪄', pinata: '🪅', nesting_dolls: '🪆',
  maracas: '🪇', flute: '🪈', harp: '🪉', shovel: '🪏', ringed_planet: '🪐',
  chair: '🪑', razor: '🪒', axe: '🪓', diya_lamp: '🪔', banjo: '🪕',
  military_helmet: '🪖', accordion: '🪗', long_drum: '🪘', coin: '🪙', carpentry_saw: '🪚',
  screwdriver: '🪛', ladder: '🪜', hook: '🪝', mirror: '🪞', window: '🪟',
  plunger: '🪠', sewing_needle: '🪡', knot: '🪢', bucket: '🪣', mouse_trap: '🪤',
  toothbrush: '🪥', headstone: '🪦', placard: '🪧', rock: '🪨', mirror_ball: '🪩',
  identification_card: '🪪', low_battery: '🪫', hamsa: '🪬', folding_hand_fan: '🪭', hair_pick: '🪮',
  khanda: '🪯', fly: '🪰', worm: '🪱', beetle: '🪲', cockroach: '🪳',
  potted_plant: '🪴', wood: '🪵', feather: '🪶', lotus: '🪷', coral: '🪸',
  empty_nest: '🪹', nest_with_eggs: '🪺', hyacinth: '🪻', jellyfish: '🪼', wing: '🪽',
  leafless_tree: '🪾', goose: '🪿', anatomical_heart: '🫀', lungs: '🫁', people_hugging: '🫂',
  pregnant_man: '🫃', pregnant_person: '🫄', person_with_crown: '🫅', fingerprint: '🫆', moose: '🫎',
  donkey: '🫏', blueberries: '🫐', bell_pepper: '🫑', olive: '🫒', flatbread: '🫓',
  tamale: '🫔', fondue: '🫕', teapot: '🫖', pouring_liquid: '🫗', beans: '🫘',
  jar: '🫙', ginger_root: '🫚', pea_pod: '🫛', root_vegetable: '🫜', splatter: '🫟',
  melting_face: '🫠', face_with_open_eyes_and_hand_over_mouth: '🫢', face_with_peeking_eye: '🫣', face_with_diagonal_mouth: '🫤', dotted_line_face: '🫥',
  biting_lip: '🫦', bubbles: '🫧', shaking_face: '🫨', face_with_bags_under_eyes: '🫩', hand_with_index_finger_and_thumb_crossed: '🫰',
  rightwards_hand: '🫱', leftwards_hand: '🫲', palm_down_hand: '🫳', palm_up_hand: '🫴', index_pointing_at_the_viewer: '🫵',
  heart_hands: '🫶', leftwards_pushing_hand: '🫷', rightwards_pushing_hand: '🫸', interrobang: '⁉️', tm: '™️',
  information_source: 'ℹ️', left_right_arrow: '↔️', arrow_up_down: '↕️', arrow_upper_left: '↖️', arrow_upper_right: '↗️',
  arrow_lower_right: '↘️', arrow_lower_left: '↙️', leftwards_arrow_with_hook: '↩️', arrow_right_hook: '↪️', watch: '⌚',
  eject: '⏏️', arrow_double_up: '⏫', arrow_double_down: '⏬', black_right_pointing_double_triangle_with_vertical_bar: '⏭️', black_left_pointing_double_triangle_with_vertical_bar: '⏮️',
  stopwatch: '⏱️', timer_clock: '⏲️', hourglass_flowing_sand: '⏳', double_vertical_bar: '⏸️', black_square_for_stop: '⏹️',
  black_circle_for_record: '⏺️', m: 'Ⓜ️', black_small_square: '▪️', white_small_square: '▫️', arrow_forward: '▶️',
  arrow_backward: '◀️', white_medium_square: '◻️', black_medium_square: '◼️', white_medium_small_square: '◽', black_medium_small_square: '◾',
  sunny: '☀️', snowman_2: '☃️', comet: '☄️', phone: '☎️', ballot_box_with_check: '☑️',
  umbrella_with_rain_drops: '☔', shamrock: '☘️', skull_and_crossbones: '☠️', biohazard_sign: '☣️', orthodox_cross: '☦️',
  star_and_crescent: '☪️', wheel_of_dharma: '☸️', white_frowning_face: '☹️', aries: '♈', taurus: '♉',
  gemini: '♊', cancer: '♋', leo: '♌', virgo: '♍', libra: '♎',
  scorpius: '♏', sagittarius: '♐', capricorn: '♑', aquarius: '♒', pisces: '♓',
  spades: '♠️', clubs: '♣️', hearts: '♥️', diamonds: '♦️', hotsprings: '♨️',
  hammer_and_pick: '⚒️', crossed_swords: '⚔️', scales: '⚖️', alembic: '⚗️', atom_symbol: '⚛️',
  fleur_de_lis: '⚜️', transgender_symbol: '⚧️', white_circle: '⚪', black_circle: '⚫', coffin: '⚰️',
  funeral_urn: '⚱️', thunder_cloud_and_rain: '⛈️', ophiuchus: '⛎', pick: '⛏️', helmet_with_white_cross: '⛑️',
  broken_chain: '⛓️‍💥', chains: '⛓️', shinto_shrine: '⛩️', church: '⛪', umbrella_on_ground: '⛱️',
  fountain: '⛲', ferry: '⛴️', boat: '⛵', skier: '⛷️', ice_skate: '⛸️',
  woman_bouncing_ball: '⛹️‍♀️', man_bouncing_ball: '⛹️‍♂️', person_with_ball: '⛹️', tent: '⛺', fuelpump: '⛽',
  email: '✉️', fist: '✊', black_nib: '✒️', latin_cross: '✝️', star_of_david: '✡️',
  eight_spoked_asterisk: '✳️', eight_pointed_black_star: '✴️', sparkle: '❇️', negative_squared_cross_mark: '❎', heavy_heart_exclamation_mark_ornament: '❣️',
  heart_on_fire: '❤️‍🔥', mending_heart: '❤️‍🩹', heavy_division_sign: '➗', curly_loop: '➰', loop: '➿',
  arrow_heading_up: '⤴️', arrow_heading_down: '⤵️', black_large_square: '⬛', white_large_square: '⬜', o: '⭕',
  wavy_dash: '〰️', part_alternation_mark: '〽️', congratulations: '㊗️', secret: '㊙️',
}

export const QUICK_REACTIONS = ['fire', 'heart', 'joy', 'eyes', 'thumbsup', '100']

export const PICKER_GROUPS: { label: string; names: string[] }[] = [
  { label: 'Hype', names: ['fire', '100', 'goat', 'crown', 'gem', 'zap', 'rocket', 'tada', 'sparkles', 'star', 'clap', 'raised_hands', 'muscle', 'salute'] },
  { label: 'Faces', names: ['joy', 'rofl', 'skull', 'sob', 'smile', 'grin', 'wink', 'heart_eyes', 'sunglasses', 'thinking', 'flushed', 'cry', 'rage', 'sweat_smile', 'shushing', 'eyes'] },
  { label: 'Hearts & hands', names: ['heart', 'purple_heart', 'broken_heart', 'thumbsup', 'thumbsdown', 'pray', 'ok_hand', 'wave'] },
  { label: 'Music', names: ['headphones', 'musical_note', 'microphone', 'cd'] },
  { label: 'Signals', names: ['white_check_mark', 'x', 'warning', 'bangbang', 'question', 'pushpin', 'lock'] },
  { label: 'More faces', names: ['relaxed', 'blush', 'innocent', 'star_struck', 'kissing_heart', 'yum', 'stuck_out_tongue', 'stuck_out_tongue_winking_eye', 'zany_face', 'partying_face', 'upside_down_face', 'money_mouth_face', 'nerd_face', 'face_with_monocle', 'smirk', 'unamused', 'roll_eyes', 'grimacing', 'relieved', 'pensive', 'sleepy', 'drooling_face', 'sleeping', 'mask', 'face_with_thermometer', 'face_with_head_bandage', 'nauseated_face', 'vomiting_face', 'sneezing_face', 'hot_face', 'cold_face', 'woozy_face', 'dizzy_face', 'exploding_head', 'cowboy_hat_face', 'clown_face', 'smiling_imp', 'imp', 'japanese_ogre', 'japanese_goblin', 'ghost', 'alien', 'robot', 'hushed', 'frowning', 'anguished', 'fearful', 'cold_sweat', 'scream', 'astonished', 'confused', 'worried', 'slightly_frowning_face', 'persevere', 'confounded', 'tired_face', 'weary', 'triumph', 'angry', 'pouting_face', 'no_mouth', 'neutral_face', 'expressionless', 'zipper_mouth_face', 'pleading_face', 'hugging_face', 'face_with_hand_over_mouth', 'shushing_face', 'face_with_raised_eyebrow', 'yawning_face', 'poop'] },
  { label: 'Gestures & body', names: ['victory_hand', 'crossed_fingers', 'love_you_gesture', 'metal', 'call_me_hand', 'point_left', 'point_right', 'point_up_2', 'point_down', 'point_up', 'middle_finger', 'raised_hand', 'vulcan_salute', 'writing_hand', 'nail_care', 'selfie', 'leg', 'foot', 'ear', 'nose', 'brain', 'eye', 'tongue', 'lips', 'tooth', 'baby', 'boy', 'girl', 'man', 'woman', 'older_man', 'older_woman', 'detective'] },
  { label: 'More hearts', names: ['blue_heart', 'green_heart', 'yellow_heart', 'orange_heart', 'black_heart', 'white_heart', 'brown_heart', 'two_hearts', 'heartpulse', 'heartbeat', 'sparkling_heart', 'cupid', 'gift_heart', 'revolving_hearts', 'heart_decoration', 'kiss'] },
  { label: 'Animals', names: ['dog', 'cat', 'mouse', 'hamster', 'rabbit', 'fox_face', 'bear', 'panda_face', 'koala', 'tiger', 'lion', 'cow', 'pig', 'frog', 'monkey_face', 'chicken', 'penguin', 'bird', 'baby_chick', 'eagle', 'duck', 'owl', 'bat', 'wolf', 'horse', 'unicorn', 'bee', 'bug', 'butterfly', 'snail', 'snake', 'turtle', 'octopus', 'fish', 'dolphin', 'whale', 'shark', 'elephant', 'giraffe_face', 'zebra_face', 'dragon_face', 'paw_prints'] },
  { label: 'Food & drink', names: ['apple', 'pizza', 'hamburger', 'fries', 'hotdog', 'taco', 'burrito', 'popcorn', 'doughnut', 'cookie', 'birthday', 'cake', 'icecream', 'candy', 'lollipop', 'chocolate_bar', 'grapes', 'watermelon', 'strawberry', 'banana', 'peach', 'cherries', 'lemon', 'avocado', 'carrot', 'corn', 'bread', 'cheese', 'egg', 'bacon', 'sushi', 'ramen', 'coffee', 'tea', 'beer', 'beers', 'wine_glass', 'cocktail', 'tropical_drink', 'champagne', 'baby_bottle', 'eggplant'] },
  { label: 'Activities & sports', names: ['soccer', 'basketball', 'football', 'baseball', 'tennis', 'volleyball', '8ball', 'bowling', 'golf', 'boxing_glove', 'trophy', 'medal_sports', 'first_place', 'dart', 'video_game', 'game_die', 'chess_pawn', 'jigsaw', 'guitar', 'violin', 'trumpet', 'saxophone', 'drum', 'dancer', 'dancers'] },
  { label: 'Travel & nature', names: ['car', 'taxi', 'bus', 'airplane', 'helicopter', 'train', 'ship', 'anchor', 'bike', 'motorcycle', 'world_map', 'mountain', 'camping', 'beach_umbrella', 'desert_island', 'stadium', 'moon', 'sun_with_face', 'full_moon', 'earth_americas', 'cloud', 'sun_behind_cloud', 'cloud_with_rain', 'snowflake', 'snowman', 'rainbow', 'droplet', 'ocean_wave', 'tornado', 'four_leaf_clover', 'maple_leaf', 'cactus', 'palm_tree', 'evergreen_tree', 'rose', 'tulip', 'sunflower', 'cherry_blossom'] },
  { label: 'Objects', names: ['tv', 'camera', 'iphone', 'computer', 'keyboard', 'battery', 'electric_plug', 'bulb', 'flashlight', 'candle', 'money_with_wings', 'dollar', 'moneybag', 'credit_card', 'gift', 'balloon', 'confetti_ball', 'ribbon', 'bell', 'mega', 'loudspeaker', 'bookmark', 'book', 'newspaper', 'pencil2', 'paperclip', 'scissors', 'hammer', 'wrench', 'gear', 'link', 'key', 'hourglass', 'alarm_clock', 'calendar', 'umbrella', 'sunglasses_obj', 'shirt', 'jeans', 'shoe'] },
  { label: 'More symbols', names: ['heavy_check_mark', 'heavy_multiplication_x', 'no_entry', 'no_entry_sign', 'exclamation', 'grey_exclamation', 'grey_question', 'heavy_plus_sign', 'heavy_minus_sign', 'infinity', 'recycle', 'radioactive', 'peace', 'yin_yang', 'om', 'wheelchair', 'id', 'new', 'ok', 'sos', 'up', 'cool', 'free', 'abc', 'arrow_right', 'arrow_left', 'arrow_up', 'arrow_down', 'arrows_counterclockwise', 'repeat', 'shuffle', 'fast_forward', 'rewind', 'play_pause', 'musical_notes', 'speaker_high_volume', 'mute', 'vibration_mode', 'clock', 'rainbow_flag'] },
  { label: 'Even more symbols', names: ['hash', 'keycap_star', 'zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'copyright', 'registered', 'a', 'b', 'o2', 'parking', 'ab', 'cl', 'ng', 'vs', 'koko', 'sa', 'u7121', 'u6307', 'u7981', 'u7a7a', 'u5408', 'u6e80', 'u6709', 'u6708', 'u7533', 'u5272', 'u55b6', 'ideograph_advantage', 'accept', 'cinema', 'atm', 'diamond_shape_with_a_dot_inside', 'currency_exchange', 'heavy_dollar_sign', 'name_badge', 'mobile_phone_off', 'no_mobile_phones', 'signal_strength', 'repeat_one', 'arrows_clockwise', 'low_brightness', 'high_brightness', 'radio_button', 'back', 'end', 'on', 'soon', 'top', 'underage', 'keycap_ten', 'capital_abcd', 'abcd', '1234', 'symbols', 'six_pointed_star', 'beginner', 'trident', 'black_square_button', 'white_square_button', 'red_circle', 'large_blue_circle', 'large_orange_diamond', 'large_blue_diamond', 'small_orange_diamond', 'small_blue_diamond', 'small_red_triangle', 'small_red_triangle_down', 'arrow_up_small', 'arrow_down_small', 'menorah_with_nine_branches', 'no_smoking', 'put_litter_in_its_place', 'do_not_litter', 'potable_water', 'non_potable_water', 'no_bicycles', 'no_pedestrians', 'children_crossing', 'mens', 'womens', 'restroom', 'baby_symbol', 'wc', 'passport_control', 'customs', 'baggage_claim', 'left_luggage', 'place_of_worship', 'wireless', 'large_orange_circle', 'large_yellow_circle', 'large_green_circle', 'large_purple_circle', 'large_brown_circle', 'large_red_square', 'large_blue_square', 'large_orange_square', 'large_yellow_square', 'large_green_square', 'large_purple_square', 'large_brown_square', 'heavy_equals_sign', 'khanda', 'splatter', 'interrobang', 'tm', 'information_source', 'left_right_arrow', 'arrow_up_down', 'arrow_upper_left', 'arrow_upper_right', 'arrow_lower_right', 'arrow_lower_left', 'leftwards_arrow_with_hook', 'arrow_right_hook', 'eject', 'arrow_double_up', 'arrow_double_down', 'black_right_pointing_double_triangle_with_vertical_bar', 'black_left_pointing_double_triangle_with_vertical_bar', 'double_vertical_bar', 'black_square_for_stop', 'black_circle_for_record', 'm', 'black_small_square', 'white_small_square', 'arrow_forward', 'arrow_backward', 'white_medium_square', 'black_medium_square', 'white_medium_small_square', 'black_medium_small_square', 'ballot_box_with_check', 'biohazard_sign', 'orthodox_cross', 'star_and_crescent', 'wheel_of_dharma', 'aries', 'taurus', 'gemini', 'cancer', 'leo', 'virgo', 'libra', 'scorpius', 'sagittarius', 'capricorn', 'aquarius', 'pisces', 'atom_symbol', 'fleur_de_lis', 'transgender_symbol', 'white_circle', 'black_circle', 'ophiuchus', 'latin_cross', 'star_of_david', 'eight_spoked_asterisk', 'eight_pointed_black_star', 'sparkle', 'negative_squared_cross_mark', 'heavy_division_sign', 'curly_loop', 'loop', 'arrow_heading_up', 'arrow_heading_down', 'black_large_square', 'white_large_square', 'o', 'wavy_dash', 'part_alternation_mark', 'congratulations', 'secret'] },
  { label: 'More activities', names: ['mahjong', 'black_joker', 'jack_o_lantern', 'christmas_tree', 'fireworks', 'sparkler', 'tanabata_tree', 'bamboo', 'dolls', 'flags', 'wind_chime', 'rice_scene', 'medal', 'reminder_ribbon', 'admission_tickets', 'fishing_pole_and_fish', 'art', 'ticket', 'performing_arts', 'slot_machine', 'flower_playing_cards', 'running_shirt_with_sash', 'ski', 'rugby_football', 'cricket_bat_and_ball', 'field_hockey_stick_and_ball', 'ice_hockey_stick_and_puck', 'table_tennis_paddle_and_ball', 'badminton_racquet_and_shuttlecock', 'gun', 'crystal_ball', 'joystick', 'frame_with_picture', 'sled', 'diving_mask', 'goal_net', 'second_place_medal', 'third_place_medal', 'martial_arts_uniform', 'curling_stone', 'lacrosse', 'softball', 'flying_disc', 'red_envelope', 'firecracker', 'thread', 'yarn', 'teddy_bear', 'yo_yo', 'kite', 'magic_wand', 'pinata', 'nesting_dolls', 'sewing_needle', 'knot', 'mirror_ball', 'spades', 'clubs', 'hearts', 'diamonds', 'ice_skate'] },
  { label: 'Flags', names: ['flag_ac', 'flag_ad', 'flag_ae', 'flag_af', 'flag_ag', 'flag_ai', 'flag_al', 'flag_am', 'flag_ao', 'flag_aq', 'flag_ar', 'flag_as', 'flag_at', 'flag_au', 'flag_aw', 'flag_ax', 'flag_az', 'flag_ba', 'flag_bb', 'flag_bd', 'flag_be', 'flag_bf', 'flag_bg', 'flag_bh', 'flag_bi', 'flag_bj', 'flag_bl', 'flag_bm', 'flag_bn', 'flag_bo', 'flag_bq', 'flag_br', 'flag_bs', 'flag_bt', 'flag_bv', 'flag_bw', 'flag_by', 'flag_bz', 'flag_ca', 'flag_cc', 'flag_cd', 'flag_cf', 'flag_cg', 'flag_ch', 'flag_ci', 'flag_ck', 'flag_cl', 'flag_cm', 'cn', 'flag_co', 'flag_cp', 'flag_sark', 'flag_cr', 'flag_cu', 'flag_cv', 'flag_cw', 'flag_cx', 'flag_cy', 'flag_cz', 'de', 'flag_dg', 'flag_dj', 'flag_dk', 'flag_dm', 'flag_do', 'flag_dz', 'flag_ea', 'flag_ec', 'flag_ee', 'flag_eg', 'flag_eh', 'flag_er', 'es', 'flag_et', 'flag_eu', 'flag_fi', 'flag_fj', 'flag_fk', 'flag_fm', 'flag_fo', 'fr', 'flag_ga', 'gb', 'flag_gd', 'flag_ge', 'flag_gf', 'flag_gg', 'flag_gh', 'flag_gi', 'flag_gl', 'flag_gm', 'flag_gn', 'flag_gp', 'flag_gq', 'flag_gr', 'flag_gs', 'flag_gt', 'flag_gu', 'flag_gw', 'flag_gy', 'flag_hk', 'flag_hm', 'flag_hn', 'flag_hr', 'flag_ht', 'flag_hu', 'flag_ic', 'flag_id', 'flag_ie', 'flag_il', 'flag_im', 'flag_in', 'flag_io', 'flag_iq', 'flag_ir', 'flag_is', 'it', 'flag_je', 'flag_jm', 'flag_jo', 'jp', 'flag_ke', 'flag_kg', 'flag_kh', 'flag_ki', 'flag_km', 'flag_kn', 'flag_kp', 'kr', 'flag_kw', 'flag_ky', 'flag_kz', 'flag_la', 'flag_lb', 'flag_lc', 'flag_li', 'flag_lk', 'flag_lr', 'flag_ls', 'flag_lt', 'flag_lu', 'flag_lv', 'flag_ly', 'flag_ma', 'flag_mc', 'flag_md', 'flag_me', 'flag_mf', 'flag_mg', 'flag_mh', 'flag_mk', 'flag_ml', 'flag_mm', 'flag_mn', 'flag_mo', 'flag_mp', 'flag_mq', 'flag_mr', 'flag_ms', 'flag_mt', 'flag_mu', 'flag_mv', 'flag_mw', 'flag_mx', 'flag_my', 'flag_mz', 'flag_na', 'flag_nc', 'flag_ne', 'flag_nf', 'flag_ng', 'flag_ni', 'flag_nl', 'flag_no', 'flag_np', 'flag_nr', 'flag_nu', 'flag_nz', 'flag_om', 'flag_pa', 'flag_pe', 'flag_pf', 'flag_pg', 'flag_ph', 'flag_pk', 'flag_pl', 'flag_pm', 'flag_pn', 'flag_pr', 'flag_ps', 'flag_pt', 'flag_pw', 'flag_py', 'flag_qa', 'flag_re', 'flag_ro', 'flag_rs', 'ru', 'flag_rw', 'flag_sa', 'flag_sb', 'flag_sc', 'flag_sd', 'flag_se', 'flag_sg', 'flag_sh', 'flag_si', 'flag_sj', 'flag_sk', 'flag_sl', 'flag_sm', 'flag_sn', 'flag_so', 'flag_sr', 'flag_ss', 'flag_st', 'flag_sv', 'flag_sx', 'flag_sy', 'flag_sz', 'flag_ta', 'flag_tc', 'flag_td', 'flag_tf', 'flag_tg', 'flag_th', 'flag_tj', 'flag_tk', 'flag_tl', 'flag_tm', 'flag_tn', 'flag_to', 'flag_tr', 'flag_tt', 'flag_tv', 'flag_tw', 'flag_tz', 'flag_ua', 'flag_ug', 'flag_um', 'flag_un', 'us', 'flag_uy', 'flag_uz', 'flag_va', 'flag_vc', 'flag_ve', 'flag_vg', 'flag_vi', 'flag_vn', 'flag_vu', 'flag_wf', 'flag_ws', 'flag_xk', 'flag_ye', 'flag_yt', 'flag_za', 'flag_zm', 'flag_zw', 'crossed_flags', 'checkered_flag', 'transgender_flag', 'waving_white_flag', 'pirate_flag', 'flag_england', 'flag_scotland', 'flag_wales', 'waving_black_flag', 'triangular_flag_on_post'] },
  { label: 'More travel & places', names: ['cyclone', 'foggy', 'closed_umbrella', 'night_with_stars', 'sunrise_over_mountains', 'sunrise', 'city_sunset', 'city_sunrise', 'bridge_at_night', 'volcano', 'milky_way', 'earth_africa', 'earth_asia', 'globe_with_meridians', 'new_moon', 'waxing_crescent_moon', 'first_quarter_moon', 'moon_2', 'waning_gibbous_moon', 'last_quarter_moon', 'waning_crescent_moon', 'new_moon_with_face', 'first_quarter_moon_with_face', 'last_quarter_moon_with_face', 'full_moon_with_face', 'star2', 'stars', 'thermometer', 'mostly_sunny', 'barely_sunny', 'partly_sunny_rain', 'snow_cloud', 'lightning', 'fog', 'wind_blowing_face', 'carousel_horse', 'ferris_wheel', 'roller_coaster', 'circus_tent', 'racing_car', 'snow_capped_mountain', 'building_construction', 'house_buildings', 'cityscape', 'derelict_house_building', 'classical_building', 'desert', 'national_park', 'house', 'house_with_garden', 'office', 'post_office', 'european_post_office', 'hospital', 'bank', 'hotel', 'love_hotel', 'convenience_store', 'school', 'department_store', 'factory', 'japanese_castle', 'european_castle', 'barber', 'wedding', 'seat', 'kaaba', 'mosque', 'synagogue', 'clock2', 'clock3', 'clock4', 'clock5', 'clock6', 'clock7', 'clock8', 'clock9', 'clock10', 'clock11', 'clock12', 'clock130', 'clock230', 'clock330', 'clock430', 'clock530', 'clock630', 'clock730', 'clock830', 'clock930', 'clock1030', 'clock1130', 'clock1230', 'mantelpiece_clock', 'mount_fuji', 'tokyo_tower', 'statue_of_liberty', 'japan', 'steam_locomotive', 'railway_car', 'bullettrain_side', 'bullettrain_front', 'metro', 'light_rail', 'station', 'tram', 'train_2', 'oncoming_bus', 'trolleybus', 'busstop', 'minibus', 'ambulance', 'fire_engine', 'police_car', 'oncoming_police_car', 'oncoming_taxi', 'oncoming_automobile', 'blue_car', 'truck', 'articulated_lorry', 'tractor', 'monorail', 'mountain_railway', 'suspension_railway', 'mountain_cableway', 'aerial_tramway', 'speedboat', 'traffic_light', 'vertical_traffic_light', 'construction', 'rotating_light', 'bellhop_bell', 'octagonal_sign', 'hindu_temple', 'hut', 'playground_slide', 'wheel', 'ring_buoy', 'oil_drum', 'motorway', 'railway_track', 'motor_boat', 'small_airplane', 'airplane_departure', 'airplane_arriving', 'satellite', 'passenger_ship', 'scooter', 'motor_scooter', 'canoe', 'flying_saucer', 'skateboard', 'auto_rickshaw', 'pickup_truck', 'roller_skate', 'motorized_wheelchair', 'manual_wheelchair', 'compass', 'bricks', 'luggage', 'parachute', 'ringed_planet', 'rock', 'wood', 'watch', 'stopwatch', 'timer_clock', 'hourglass_flowing_sand', 'sunny', 'snowman_2', 'comet', 'umbrella_with_rain_drops', 'hotsprings', 'thunder_cloud_and_rain', 'shinto_shrine', 'church', 'umbrella_on_ground', 'fountain', 'ferry', 'boat', 'tent', 'fuelpump'] },
  { label: 'More food & drink', names: ['chestnut', 'hot_pepper', 'brown_mushroom', 'tomato', 'melon', 'tangerine', 'lime', 'pineapple', 'green_apple', 'pear', 'meat_on_bone', 'poultry_leg', 'rice_cracker', 'rice_ball', 'rice', 'curry', 'spaghetti', 'sweet_potato', 'dango', 'oden', 'fried_shrimp', 'fish_cake', 'shaved_ice', 'ice_cream', 'custard', 'honey_pot', 'bento', 'stew', 'fried_egg', 'fork_and_knife', 'sake', 'knife_fork_plate', 'amphora', 'hocho', 'clinking_glasses', 'tumbler_glass', 'spoon', 'croissant', 'cucumber', 'potato', 'baguette_bread', 'green_salad', 'shallow_pan_of_food', 'stuffed_flatbread', 'glass_of_milk', 'peanuts', 'kiwifruit', 'pancakes', 'dumpling', 'fortune_cookie', 'takeout_box', 'chopsticks', 'bowl_with_spoon', 'cup_with_straw', 'coconut', 'broccoli', 'pie', 'pretzel', 'cut_of_meat', 'sandwich', 'canned_food', 'leafy_green', 'mango', 'moon_cake', 'bagel', 'cupcake', 'salt', 'beverage_box', 'garlic', 'onion', 'falafel', 'waffle', 'butter', 'mate_drink', 'ice_cube', 'bubble_tea', 'blueberries', 'bell_pepper', 'olive', 'flatbread', 'tamale', 'fondue', 'teapot', 'pouring_liquid', 'beans', 'jar', 'ginger_root', 'pea_pod', 'root_vegetable'] },
  { label: 'More animals & nature', names: ['seedling', 'deciduous_tree', 'hibiscus', 'blossom', 'ear_of_rice', 'herb', 'fallen_leaf', 'leaves', 'mushroom', 'rosette', 'rat', 'mouse2', 'ox', 'water_buffalo', 'cow2', 'tiger2', 'leopard', 'rabbit2', 'black_cat', 'cat2', 'dragon', 'crocodile', 'whale2', 'racehorse', 'ram', 'sheep', 'monkey', 'rooster', 'service_dog', 'dog2', 'pig2', 'boar', 'shell', 'ant', 'ladybug', 'tropical_fish', 'blowfish', 'hatching_chick', 'hatched_chick', 'phoenix', 'black_bird', 'poodle', 'dromedary_camel', 'camel', 'polar_bear', 'pig_nose', 'chipmunk', 'bouquet', 'white_flower', 'dove_of_peace', 'spider', 'spider_web', 'wilted_flower', 'crab', 'scorpion', 'turkey', 'deer', 'gorilla', 'lizard', 'rhinoceros', 'shrimp', 'squid', 'hedgehog', 'sauropod', 't_rex', 'cricket', 'kangaroo', 'llama', 'peacock', 'hippopotamus', 'parrot', 'raccoon', 'lobster', 'mosquito', 'microbe', 'badger', 'swan', 'mammoth', 'dodo', 'sloth', 'otter', 'orangutan', 'skunk', 'flamingo', 'oyster', 'beaver', 'bison', 'seal', 'guide_dog', 'fly', 'worm', 'beetle', 'cockroach', 'potted_plant', 'feather', 'lotus', 'coral', 'empty_nest', 'nest_with_eggs', 'hyacinth', 'jellyfish', 'wing', 'leafless_tree', 'goose', 'moose', 'donkey', 'shamrock'] },
  { label: 'People', names: ['santa', 'snowboarder', 'woman_running', 'woman_running_facing_right', 'man_running', 'man_running_facing_right', 'person_running_facing_right', 'runner', 'woman_surfing', 'man_surfing', 'surfer', 'horse_racing', 'woman_swimming', 'man_swimming', 'swimmer', 'woman_lifting_weights', 'man_lifting_weights', 'weight_lifter', 'woman_golfing', 'man_golfing', 'golfer', 'facepunch', 'open_hands', 'footprints', 'bust_in_silhouette', 'busts_in_silhouette', 'male_farmer', 'male_cook', 'man_feeding_baby', 'male_student', 'male_singer', 'male_artist', 'male_teacher', 'male_factory_worker', 'man_boy_boy', 'man_boy', 'man_girl_boy', 'man_girl_girl', 'man_girl', 'man_man_boy', 'man_man_boy_boy', 'man_man_girl', 'man_man_girl_boy', 'man_man_girl_girl', 'man_woman_boy', 'man_woman_boy_boy', 'man_woman_girl', 'man_woman_girl_boy', 'man_woman_girl_girl', 'male_technologist', 'male_office_worker', 'male_mechanic', 'male_scientist', 'male_astronaut', 'male_firefighter', 'man_with_white_cane_facing_right', 'man_with_probing_cane', 'red_haired_man', 'curly_haired_man', 'bald_man', 'white_haired_man', 'man_in_motorized_wheelchair_facing_right', 'man_in_motorized_wheelchair', 'man_in_manual_wheelchair_facing_right', 'man_in_manual_wheelchair', 'male_doctor', 'male_judge', 'male_pilot', 'man_heart_man', 'man_kiss_man', 'female_farmer', 'female_cook', 'woman_feeding_baby', 'female_student', 'female_singer', 'female_artist', 'female_teacher', 'female_factory_worker', 'woman_boy_boy', 'woman_boy', 'woman_girl_boy', 'woman_girl_girl', 'woman_girl', 'woman_woman_boy', 'woman_woman_boy_boy', 'woman_woman_girl', 'woman_woman_girl_boy', 'woman_woman_girl_girl', 'female_technologist', 'female_office_worker', 'female_mechanic', 'female_scientist', 'female_astronaut', 'female_firefighter', 'woman_with_white_cane_facing_right', 'woman_with_probing_cane', 'red_haired_woman', 'curly_haired_woman', 'bald_woman', 'white_haired_woman', 'woman_in_motorized_wheelchair_facing_right', 'woman_in_motorized_wheelchair', 'woman_in_manual_wheelchair_facing_right', 'woman_in_manual_wheelchair', 'female_doctor', 'female_judge', 'female_pilot', 'woman_heart_man', 'woman_heart_woman', 'woman_kiss_man', 'woman_kiss_woman', 'family', 'man_and_woman_holding_hands', 'two_men_holding_hands', 'two_women_holding_hands', 'female_police_officer', 'male_police_officer', 'cop', 'women_with_bunny_ears_partying', 'men_with_bunny_ears_partying', 'woman_with_veil', 'man_with_veil', 'bride_with_veil', 'blond_haired_woman', 'blond_haired_man', 'person_with_blond_hair', 'man_with_gua_pi_mao', 'woman_wearing_turban', 'man_wearing_turban', 'man_with_turban', 'female_construction_worker', 'male_construction_worker', 'construction_worker', 'princess', 'angel', 'woman_tipping_hand', 'man_tipping_hand', 'information_desk_person', 'female_guard', 'male_guard', 'guardsman', 'woman_getting_massage', 'man_getting_massage', 'massage', 'woman_getting_haircut', 'man_getting_haircut', 'haircut', 'couplekiss', 'couple_with_heart', 'man_in_business_suit_levitating', 'female_detective', 'male_detective', 'man_dancing', 'raised_hand_with_fingers_splayed', 'speaking_head_in_silhouette', 'woman_gesturing_no', 'man_gesturing_no', 'no_good', 'woman_gesturing_ok', 'man_gesturing_ok', 'ok_woman', 'woman_bowing', 'man_bowing', 'bow', 'woman_raising_hand', 'man_raising_hand', 'raising_hand', 'woman_frowning', 'man_frowning', 'person_frowning', 'woman_pouting', 'man_pouting', 'person_with_pouting_face', 'woman_rowing_boat', 'man_rowing_boat', 'rowboat', 'woman_biking', 'man_biking', 'bicyclist', 'woman_mountain_biking', 'man_mountain_biking', 'mountain_bicyclist', 'woman_walking', 'woman_walking_facing_right', 'man_walking', 'man_walking_facing_right', 'person_walking_facing_right', 'walking', 'bath', 'sleeping_accommodation', 'pinched_fingers', 'pinching_hand', 'raised_back_of_hand', 'left_facing_fist', 'right_facing_fist', 'handshake', 'woman_facepalming', 'man_facepalming', 'face_palm', 'pregnant_woman', 'breast_feeding', 'palms_up_together', 'prince', 'woman_in_tuxedo', 'man_in_tuxedo', 'person_in_tuxedo', 'mrs_claus', 'woman_shrugging', 'man_shrugging', 'shrug', 'woman_cartwheeling', 'man_cartwheeling', 'person_doing_cartwheel', 'woman_juggling', 'man_juggling', 'juggling', 'fencer', 'woman_wrestling', 'man_wrestling', 'wrestlers', 'woman_playing_water_polo', 'man_playing_water_polo', 'water_polo', 'woman_playing_handball', 'man_playing_handball', 'handball', 'ninja', 'bone', 'female_superhero', 'male_superhero', 'superhero', 'female_supervillain', 'male_supervillain', 'supervillain', 'ear_with_hearing_aid', 'mechanical_arm', 'mechanical_leg', 'troll', 'woman_standing', 'man_standing', 'standing_person', 'woman_kneeling', 'woman_kneeling_facing_right', 'man_kneeling', 'man_kneeling_facing_right', 'person_kneeling_facing_right', 'kneeling_person', 'deaf_woman', 'deaf_man', 'deaf_person', 'farmer', 'cook', 'person_feeding_baby', 'mx_claus', 'student', 'singer', 'artist', 'teacher', 'factory_worker', 'technologist', 'office_worker', 'mechanic', 'scientist', 'astronaut', 'firefighter', 'people_holding_hands', 'person_with_white_cane_facing_right', 'person_with_probing_cane', 'red_haired_person', 'curly_haired_person', 'bald_person', 'white_haired_person', 'person_in_motorized_wheelchair_facing_right', 'person_in_motorized_wheelchair', 'person_in_manual_wheelchair_facing_right', 'person_in_manual_wheelchair', 'family_adult_adult_child', 'family_adult_adult_child_child', 'family_adult_child_child', 'family_adult_child', 'health_worker', 'judge', 'pilot', 'adult', 'child', 'older_adult', 'woman_with_beard', 'man_with_beard', 'bearded_person', 'person_with_headscarf', 'woman_in_steamy_room', 'man_in_steamy_room', 'person_in_steamy_room', 'woman_climbing', 'man_climbing', 'person_climbing', 'woman_in_lotus_position', 'man_in_lotus_position', 'person_in_lotus_position', 'female_mage', 'male_mage', 'mage', 'female_fairy', 'male_fairy', 'fairy', 'female_vampire', 'male_vampire', 'vampire', 'mermaid', 'merman', 'merperson', 'female_elf', 'male_elf', 'elf', 'female_genie', 'male_genie', 'genie', 'female_zombie', 'male_zombie', 'zombie', 'anatomical_heart', 'lungs', 'people_hugging', 'pregnant_man', 'pregnant_person', 'person_with_crown', 'fingerprint', 'biting_lip', 'hand_with_index_finger_and_thumb_crossed', 'rightwards_hand', 'leftwards_hand', 'palm_down_hand', 'palm_up_hand', 'index_pointing_at_the_viewer', 'heart_hands', 'leftwards_pushing_hand', 'rightwards_pushing_hand', 'skier', 'woman_bouncing_ball', 'man_bouncing_ball', 'person_with_ball', 'fist'] },
  { label: 'More objects', names: ['school_satchel', 'mortar_board', 'studio_microphone', 'level_slider', 'control_knobs', 'film_frames', 'movie_camera', 'tophat', 'clapper', 'musical_keyboard', 'musical_score', 'izakaya_lantern', 'label', 'bow_and_arrow', 'womans_hat', 'eyeglasses', 'necktie', 'dress', 'kimono', 'bikini', 'womans_clothes', 'purse', 'handbag', 'pouch', 'athletic_shoe', 'high_heel', 'sandal', 'boot', 'lipstick', 'syringe', 'pill', 'ring', 'bomb', 'yen', 'euro', 'pound', 'chart', 'briefcase', 'minidisc', 'floppy_disk', 'dvd', 'file_folder', 'open_file_folder', 'page_with_curl', 'page_facing_up', 'calendar_2', 'card_index', 'chart_with_upwards_trend', 'chart_with_downwards_trend', 'bar_chart', 'clipboard', 'round_pushpin', 'straight_ruler', 'triangular_ruler', 'bookmark_tabs', 'ledger', 'notebook', 'notebook_with_decorative_cover', 'closed_book', 'green_book', 'blue_book', 'orange_book', 'books', 'scroll', 'memo', 'telephone_receiver', 'pager', 'fax', 'satellite_antenna', 'outbox_tray', 'inbox_tray', 'package', 'e_mail', 'incoming_envelope', 'envelope_with_arrow', 'mailbox_closed', 'mailbox', 'mailbox_with_mail', 'mailbox_with_no_mail', 'postbox', 'postal_horn', 'calling', 'camera_with_flash', 'video_camera', 'radio', 'vhs', 'film_projector', 'prayer_beads', 'speaker', 'sound', 'mag', 'mag_right', 'lock_with_ink_pen', 'closed_lock_with_key', 'unlock', 'no_bell', 'nut_and_bolt', 'microscope', 'telescope', 'linked_paperclips', 'lower_left_ballpoint_pen', 'lower_left_fountain_pen', 'lower_left_paintbrush', 'lower_left_crayon', 'desktop_computer', 'printer', 'three_button_mouse', 'trackball', 'card_index_dividers', 'card_file_box', 'file_cabinet', 'wastebasket', 'spiral_note_pad', 'spiral_calendar_pad', 'compression', 'old_key', 'rolled_up_newspaper', 'dagger_knife', 'ballot_box_with_ballot', 'moyai', 'door', 'smoking', 'toilet', 'shower', 'bathtub', 'couch_and_lamp', 'shopping_bags', 'bed', 'shopping_trolley', 'elevator', 'hammer_and_wrench', 'shield', 'sari', 'lab_coat', 'goggles', 'hiking_boot', 'womans_flat_shoe', 'probing_cane', 'safety_vest', 'billed_cap', 'scarf', 'gloves', 'coat', 'socks', 'test_tube', 'petri_dish', 'dna', 'abacus', 'fire_extinguisher', 'toolbox', 'magnet', 'lotion_bottle', 'safety_pin', 'broom', 'basket', 'roll_of_paper', 'soap', 'sponge', 'receipt', 'nazar_amulet', 'ballet_shoes', 'one_piece_swimsuit', 'briefs', 'shorts', 'thong_sandal', 'drop_of_blood', 'adhesive_bandage', 'stethoscope', 'x_ray', 'crutch', 'boomerang', 'maracas', 'flute', 'harp', 'shovel', 'chair', 'razor', 'axe', 'diya_lamp', 'banjo', 'military_helmet', 'accordion', 'long_drum', 'coin', 'carpentry_saw', 'screwdriver', 'ladder', 'hook', 'mirror', 'window', 'plunger', 'bucket', 'mouse_trap', 'toothbrush', 'headstone', 'placard', 'identification_card', 'low_battery', 'hamsa', 'folding_hand_fan', 'hair_pick', 'bubbles', 'phone', 'hammer_and_pick', 'crossed_swords', 'scales', 'alembic', 'coffin', 'funeral_urn', 'pick', 'helmet_with_white_cross', 'broken_chain', 'chains', 'email', 'black_nib'] },
  { label: 'More smileys', names: ['eye_in_speech_bubble', 'space_invader', 'love_letter', 'anger', 'zzz', 'boom', 'sweat_drops', 'dash', 'dizzy', 'speech_balloon', 'thought_balloon', 'hole', 'left_speech_bubble', 'right_anger_bubble', 'grinning', 'smiley', 'laughing', 'sweat', 'kissing', 'kissing_smiling_eyes', 'kissing_closed_eyes', 'stuck_out_tongue_closed_eyes', 'disappointed', 'disappointed_relieved', 'face_exhaling', 'open_mouth', 'face_with_spiral_eyes', 'face_in_clouds', 'smile_cat', 'joy_cat', 'smiley_cat', 'heart_eyes_cat', 'smirk_cat', 'kissing_cat', 'pouting_cat', 'crying_cat_face', 'scream_cat', 'head_shaking_horizontally', 'head_shaking_vertically', 'slightly_smiling_face', 'see_no_evil', 'hear_no_evil', 'speak_no_evil', 'lying_face', 'face_with_symbols_on_mouth', 'smiling_face_with_3_hearts', 'smiling_face_with_tear', 'disguised_face', 'face_holding_back_tears', 'light_blue_heart', 'grey_heart', 'pink_heart', 'melting_face', 'face_with_open_eyes_and_hand_over_mouth', 'face_with_peeking_eye', 'face_with_diagonal_mouth', 'dotted_line_face', 'shaking_face', 'face_with_bags_under_eyes', 'skull_and_crossbones', 'white_frowning_face', 'heavy_heart_exclamation_mark_ornament', 'heart_on_fire', 'mending_heart'] },
]

export function emojiGlyph(name: string): string {
  return EMOJI[name] ?? name
}

// iOS-style PNGs for every glyph above, keyed by the same shortcode name.
const iosImages = import.meta.glob('../../assets/emoji/apple/*.png', { eager: true, import: 'default' }) as Record<string, string>
export const EMOJI_IMG: Record<string, string> = {}
for (const [path, url] of Object.entries(iosImages)) {
  const name = path.slice(path.lastIndexOf('/') + 1, -'.png'.length)
  EMOJI_IMG[name] = url
}

// Reverse lookup so raw glyphs typed or pasted into message text can be
// swapped for their iOS image too, longest glyph first to prefer full
// sequences (e.g. the heart's variation selector) over bare prefixes.
export const NAME_BY_GLYPH: Record<string, string> = Object.fromEntries(
  Object.entries(EMOJI).map(([name, glyph]) => [glyph, name]),
)
export const GLYPHS_BY_LENGTH_DESC = Object.values(EMOJI).sort((a, b) => b.length - a.length)

const RECENT_KEY = 'unreleased:chat:recentEmoji'

export function recentEmoji(): string[] {
  try {
    const list = JSON.parse(localStorage.getItem(RECENT_KEY) ?? '[]') as string[]
    return Array.isArray(list) ? list.slice(0, 8) : []
  } catch {
    return []
  }
}

export function rememberEmoji(name: string): void {
  try {
    const next = [name, ...recentEmoji().filter((n) => n !== name)].slice(0, 8)
    localStorage.setItem(RECENT_KEY, JSON.stringify(next))
  } catch {}
}

// Most-recently-used reactions first, padded out with the defaults so the
// quick-react row always has `count` options even before a user reacts.
export function quickReactions(count = 3): string[] {
  const recent = recentEmoji()
  const merged = [...recent, ...QUICK_REACTIONS.filter((n) => !recent.includes(n))]
  return merged.slice(0, count)
}
